"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .appuser import AppUser, AppUserTypedDict
from openapi.types import BaseModel
import pydantic
from typing import Optional, TypedDict
from typing_extensions import Annotated, NotRequired


class AppUserViewTypedDict(TypedDict):
    r"""The AppUserView contains an app user as well as paths for apps, identity users, and last usage in expanded arrays."""
    
    app_user: NotRequired[AppUserTypedDict]
    r"""Application User that represents an account in the application."""
    app_path: NotRequired[str]
    r"""JSONPATH expression indicating where the app is expanded in expanded arrays indicated in the request."""
    identity_user_path: NotRequired[str]
    r"""JSONPATH expression indicating where the identity user is expanded in expanded arrays indicated in the request."""
    last_usage_path: NotRequired[str]
    r"""JSONPATH expression indicating where the last usage information is expanded in expanded arrays indicated in the request."""
    

class AppUserView(BaseModel):
    r"""The AppUserView contains an app user as well as paths for apps, identity users, and last usage in expanded arrays."""
    
    app_user: Annotated[Optional[AppUser], pydantic.Field(alias="appUser")] = None
    r"""Application User that represents an account in the application."""
    app_path: Annotated[Optional[str], pydantic.Field(alias="appPath")] = None
    r"""JSONPATH expression indicating where the app is expanded in expanded arrays indicated in the request."""
    identity_user_path: Annotated[Optional[str], pydantic.Field(alias="identityUserPath")] = None
    r"""JSONPATH expression indicating where the identity user is expanded in expanded arrays indicated in the request."""
    last_usage_path: Annotated[Optional[str], pydantic.Field(alias="lastUsagePath")] = None
    r"""JSONPATH expression indicating where the last usage information is expanded in expanded arrays indicated in the request."""
    
