"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from openapi.types import BaseModel
from typing import TypedDict


class DirectoryServiceDeleteResponseTypedDict(TypedDict):
    r"""Empty response with a status code indicating success."""
    
    

class DirectoryServiceDeleteResponse(BaseModel):
    r"""Empty response with a status code indicating success."""
    
    
