"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .appentitlementuserbinding import AppEntitlementUserBinding, AppEntitlementUserBindingTypedDict
from openapi.types import BaseModel, Nullable, OptionalNullable, UNSET, UNSET_SENTINEL
from pydantic import model_serializer
from typing import List, TypedDict
from typing_extensions import NotRequired


class ListAppUsersForIdentityWithGrantResponseTypedDict(TypedDict):
    r"""The ListAppUsersForIdentityWithGrantResponse message."""
    
    bindings: NotRequired[Nullable[List[AppEntitlementUserBindingTypedDict]]]
    r"""The list of app users that may also have grant information."""
    

class ListAppUsersForIdentityWithGrantResponse(BaseModel):
    r"""The ListAppUsersForIdentityWithGrantResponse message."""
    
    bindings: OptionalNullable[List[AppEntitlementUserBinding]] = UNSET
    r"""The list of app users that may also have grant information."""
    
    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = ["bindings"]
        nullable_fields = ["bindings"]
        null_default_fields = []

        serialized = handler(self)

        m = {}

        for n, f in self.model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val is not None and val != UNSET_SENTINEL:
                m[k] = val
            elif val != UNSET_SENTINEL and (
                not k in optional_fields
                or (
                    k in optional_fields
                    and k in nullable_fields
                    and (
                        self.__pydantic_fields_set__.intersection({n})
                        or k in null_default_fields
                    )  # pylint: disable=no-member
                )
            ):
                m[k] = val

        return m
        
