"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from openapi.types import BaseModel
from typing import TypedDict


class RequestCatalogManagementServiceAddAccessEntitlementsResponseTypedDict(TypedDict):
    r"""Empty response with a status code indicating success."""
    
    

class RequestCatalogManagementServiceAddAccessEntitlementsResponse(BaseModel):
    r"""Empty response with a status code indicating success."""
    
    
