"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from openapi.types import BaseModel
from typing import Optional, TypedDict
from typing_extensions import NotRequired


class ResponseTestTypedDict(TypedDict):
    r"""The ResponseTest message."""
    
    version: NotRequired[str]
    r"""version contains the constant value \"v1\". Future versions of the Webhook Response
    will use a different string.
    """
    

class ResponseTest(BaseModel):
    r"""The ResponseTest message."""
    
    version: Optional[str] = None
    r"""version contains the constant value \"v1\". Future versions of the Webhook Response
    will use a different string.
    """
    
