"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .webhook import Webhook, WebhookTypedDict
from openapi.types import BaseModel
from typing import Optional, TypedDict
from typing_extensions import NotRequired


class WebhooksServiceCreateResponseTypedDict(TypedDict):
    r"""The WebhooksServiceCreateResponse message."""
    
    webhook: NotRequired[WebhookTypedDict]
    r"""The Webhook message."""
    

class WebhooksServiceCreateResponse(BaseModel):
    r"""The WebhooksServiceCreateResponse message."""
    
    webhook: Optional[Webhook] = None
    r"""The Webhook message."""
    
