"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from sdk.types import BaseModel
from typing_extensions import TypedDict


class AccountInContextTypedDict(TypedDict):
    r"""The AccountInContext message."""


class AccountInContext(BaseModel):
    r"""The AccountInContext message."""
