"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from datetime import datetime
import pydantic
from sdk.types import BaseModel
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class ActionOutcomeCancelledTypedDict(TypedDict):
    r"""The ActionOutcomeCancelled message."""

    outcome_time: NotRequired[datetime]


class ActionOutcomeCancelled(BaseModel):
    r"""The ActionOutcomeCancelled message."""

    outcome_time: Annotated[Optional[datetime], pydantic.Field(alias="outcomeTime")] = (
        None
    )
