"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .appentitlementref import AppEntitlementRef, AppEntitlementRefTypedDict
from datetime import datetime
import pydantic
from pydantic import model_serializer
from sdk.types import BaseModel, Nullable, OptionalNullable, UNSET, UNSET_SENTINEL
from typing import List, Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class AppEntitlementUserBindingTypedDict(TypedDict):
    r"""The AppEntitlementUserBinding represents the relationship that gives an app user access to an app entitlement"""

    app_entitlement_id: NotRequired[str]
    r"""The ID of the app entitlement that the app user has access to"""
    app_id: NotRequired[str]
    r"""The ID of the app associated with the app entitlement"""
    app_user_id: NotRequired[str]
    r"""The ID of the app user that has access to the app entitlement"""
    created_at: NotRequired[datetime]
    deleted_at: NotRequired[datetime]
    deprovision_at: NotRequired[datetime]
    grant_sources: NotRequired[Nullable[List[AppEntitlementRefTypedDict]]]
    r"""The grantSources field."""


class AppEntitlementUserBinding(BaseModel):
    r"""The AppEntitlementUserBinding represents the relationship that gives an app user access to an app entitlement"""

    app_entitlement_id: Annotated[
        Optional[str], pydantic.Field(alias="appEntitlementId")
    ] = None
    r"""The ID of the app entitlement that the app user has access to"""

    app_id: Annotated[Optional[str], pydantic.Field(alias="appId")] = None
    r"""The ID of the app associated with the app entitlement"""

    app_user_id: Annotated[Optional[str], pydantic.Field(alias="appUserId")] = None
    r"""The ID of the app user that has access to the app entitlement"""

    created_at: Annotated[Optional[datetime], pydantic.Field(alias="createdAt")] = None

    deleted_at: Annotated[Optional[datetime], pydantic.Field(alias="deletedAt")] = None

    deprovision_at: Annotated[
        Optional[datetime], pydantic.Field(alias="deprovisionAt")
    ] = None

    grant_sources: Annotated[
        OptionalNullable[List[AppEntitlementRef]], pydantic.Field(alias="grantSources")
    ] = UNSET
    r"""The grantSources field."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = [
            "appEntitlementId",
            "appId",
            "appUserId",
            "createdAt",
            "deletedAt",
            "deprovisionAt",
            "grantSources",
        ]
        nullable_fields = ["grantSources"]
        null_default_fields = []

        serialized = handler(self)

        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)
            serialized.pop(k, None)

            optional_nullable = k in optional_fields and k in nullable_fields
            is_set = (
                self.__pydantic_fields_set__.intersection({n})
                or k in null_default_fields
            )  # pylint: disable=no-member

            if val is not None and val != UNSET_SENTINEL:
                m[k] = val
            elif val != UNSET_SENTINEL and (
                not k in optional_fields or (optional_nullable and is_set)
            ):
                m[k] = val

        return m
