"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses


@dataclasses.dataclass
class AppOwnerApprovalInput:
    r"""App owner approval provides the configuration for an approval step when the app owner is the target."""
    

