"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from sdk.types import BaseModel
from typing import TypedDict


class ConnectorServiceDeleteResponseTypedDict(TypedDict):
    r"""Empty response body. Status code indicates success."""
    
    

class ConnectorServiceDeleteResponse(BaseModel):
    r"""Empty response body. Status code indicates success."""
    
    
