"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses



@dataclasses.dataclass
class ConnectorServiceDeleteRequest:
    r"""ConnectorServiceDeleteRequest is a request for deleting a connector. It uses URL values for input."""
    

