"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum
import pydantic
from pydantic import field_serializer, model_serializer
from pydantic.functional_validators import PlainValidator
from sdk import utils
from sdk.models import shared
from sdk.types import BaseModel, Nullable, OptionalNullable, UNSET, UNSET_SENTINEL
from sdk.utils import validate_open_enum
from typing import List, Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class CreateAppRequestIdentityMatching(str, Enum, metaclass=utils.OpenEnumMeta):
    r"""Define the app user identity matching strategy for this app."""

    APP_USER_IDENTITY_MATCHING_UNSPECIFIED = "APP_USER_IDENTITY_MATCHING_UNSPECIFIED"
    APP_USER_IDENTITY_MATCHING_STRICT = "APP_USER_IDENTITY_MATCHING_STRICT"
    APP_USER_IDENTITY_MATCHING_DISPLAY_NAME = "APP_USER_IDENTITY_MATCHING_DISPLAY_NAME"


class CreateAppRequestTypedDict(TypedDict):
    r"""The CreateAppRequest message is used to create a new app."""

    display_name: str
    r"""Creates the app with this display name."""
    certify_policy_id: NotRequired[str]
    r"""Creates the app with this certify policy."""
    description: NotRequired[str]
    r"""Creates the app with this description."""
    grant_policy_id: NotRequired[str]
    r"""Creates the app with this grant policy."""
    identity_matching: NotRequired[CreateAppRequestIdentityMatching]
    r"""Define the app user identity matching strategy for this app."""
    monthly_cost_usd: NotRequired[int]
    r"""Creates the app with this monthly cost per seat."""
    owners: NotRequired[Nullable[List[str]]]
    r"""Creates the app with this array of owners."""
    revoke_policy_id: NotRequired[str]
    r"""Creates the app with this revoke policy."""
    strict_access_entitlement_provisioning: NotRequired[bool]
    r"""This flag enforces a provisioning mode where the access entitlement is always included in the provisioning flow, if the app user doesn't exist"""


class CreateAppRequest(BaseModel):
    r"""The CreateAppRequest message is used to create a new app."""

    display_name: Annotated[str, pydantic.Field(alias="displayName")]
    r"""Creates the app with this display name."""

    certify_policy_id: Annotated[
        Optional[str], pydantic.Field(alias="certifyPolicyId")
    ] = None
    r"""Creates the app with this certify policy."""

    description: Optional[str] = None
    r"""Creates the app with this description."""

    grant_policy_id: Annotated[Optional[str], pydantic.Field(alias="grantPolicyId")] = (
        None
    )
    r"""Creates the app with this grant policy."""

    identity_matching: Annotated[
        Annotated[
            Optional[CreateAppRequestIdentityMatching],
            PlainValidator(validate_open_enum(False)),
        ],
        pydantic.Field(alias="identityMatching"),
    ] = None
    r"""Define the app user identity matching strategy for this app."""

    monthly_cost_usd: Annotated[
        Optional[int], pydantic.Field(alias="monthlyCostUsd")
    ] = None
    r"""Creates the app with this monthly cost per seat."""

    owners: OptionalNullable[List[str]] = UNSET
    r"""Creates the app with this array of owners."""

    revoke_policy_id: Annotated[
        Optional[str], pydantic.Field(alias="revokePolicyId")
    ] = None
    r"""Creates the app with this revoke policy."""

    strict_access_entitlement_provisioning: Annotated[
        Optional[bool], pydantic.Field(alias="strictAccessEntitlementProvisioning")
    ] = None
    r"""This flag enforces a provisioning mode where the access entitlement is always included in the provisioning flow, if the app user doesn't exist"""

    @field_serializer("identity_matching")
    def serialize_identity_matching(self, value):
        if isinstance(value, str):
            try:
                return shared.CreateAppRequestIdentityMatching(value)
            except ValueError:
                return value
        return value

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = [
            "certifyPolicyId",
            "description",
            "grantPolicyId",
            "identityMatching",
            "monthlyCostUsd",
            "owners",
            "revokePolicyId",
            "strictAccessEntitlementProvisioning",
        ]
        nullable_fields = ["owners"]
        null_default_fields = []

        serialized = handler(self)

        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)
            serialized.pop(k, None)

            optional_nullable = k in optional_fields and k in nullable_fields
            is_set = (
                self.__pydantic_fields_set__.intersection({n})
                or k in null_default_fields
            )  # pylint: disable=no-member

            if val is not None and val != UNSET_SENTINEL:
                m[k] = val
            elif val != UNSET_SENTINEL and (
                not k in optional_fields or (optional_nullable and is_set)
            ):
                m[k] = val

        return m
