"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
from ..shared import directoryview as shared_directoryview
from dataclasses_json import Undefined, dataclass_json
from sdk import utils
from typing import Any, Optional


@dataclass_json(undefined=Undefined.EXCLUDE)

@dataclasses.dataclass
class DirectoryServiceGetResponse:
    r"""The Directory Service Get Response returns a directory view with a directory and JSONPATHs indicating the
     location in the expanded array that items are expanded as indicated by the expand mask in the request.
    """
    directory_view: Optional[shared_directoryview.DirectoryView] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('directoryView'), 'exclude': lambda f: f is None }})
    r"""The directory view contains a directory and an app_path which is a JSONPATH set to the location in the expand mask that the expanded app will live if requested by the expander."""
    expanded: Optional[list[dict[str, Any]]] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('expanded') }})
    r"""List of serialized related objects."""
    

