"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from sdk.types import BaseModel
from typing_extensions import TypedDict


class DisabledReasonCircuitBreakerTypedDict(TypedDict):
    r"""The DisabledReasonCircuitBreaker message."""


class DisabledReasonCircuitBreaker(BaseModel):
    r"""The DisabledReasonCircuitBreaker message."""
