"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
import pydantic
from pydantic import model_serializer
from sdk.types import BaseModel, Nullable, OptionalNullable, UNSET, UNSET_SENTINEL
from typing import List, Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class DoubleRulesTypedDict(TypedDict):
    r"""DoubleRules describes the constraints applied to `double` values"""

    const: NotRequired[float]
    r"""Const specifies that this field must be exactly the specified value"""
    gt: NotRequired[float]
    r"""Gt specifies that this field must be greater than the specified value,
    exclusive. If the value of Gt is larger than a specified Lt or Lte, the
    range is reversed.
    """
    gte: NotRequired[float]
    r"""Gte specifies that this field must be greater than or equal to the
    specified value, inclusive. If the value of Gte is larger than a
    specified Lt or Lte, the range is reversed.
    """
    ignore_empty: NotRequired[bool]
    r"""IgnoreEmpty specifies that the validation rules of this field should be
    evaluated only if the field is not empty
    """
    in_: NotRequired[Nullable[List[float]]]
    r"""In specifies that this field must be equal to one of the specified
    values
    """
    lt: NotRequired[float]
    r"""Lt specifies that this field must be less than the specified value,
    exclusive
    """
    lte: NotRequired[float]
    r"""Lte specifies that this field must be less than or equal to the
    specified value, inclusive
    """
    not_in: NotRequired[Nullable[List[float]]]
    r"""NotIn specifies that this field cannot be equal to one of the specified
    values
    """


class DoubleRules(BaseModel):
    r"""DoubleRules describes the constraints applied to `double` values"""

    const: Optional[float] = None
    r"""Const specifies that this field must be exactly the specified value"""

    gt: Optional[float] = None
    r"""Gt specifies that this field must be greater than the specified value,
    exclusive. If the value of Gt is larger than a specified Lt or Lte, the
    range is reversed.
    """

    gte: Optional[float] = None
    r"""Gte specifies that this field must be greater than or equal to the
    specified value, inclusive. If the value of Gte is larger than a
    specified Lt or Lte, the range is reversed.
    """

    ignore_empty: Annotated[Optional[bool], pydantic.Field(alias="ignoreEmpty")] = None
    r"""IgnoreEmpty specifies that the validation rules of this field should be
    evaluated only if the field is not empty
    """

    in_: Annotated[OptionalNullable[List[float]], pydantic.Field(alias="in")] = UNSET
    r"""In specifies that this field must be equal to one of the specified
    values
    """

    lt: Optional[float] = None
    r"""Lt specifies that this field must be less than the specified value,
    exclusive
    """

    lte: Optional[float] = None
    r"""Lte specifies that this field must be less than or equal to the
    specified value, inclusive
    """

    not_in: Annotated[OptionalNullable[List[float]], pydantic.Field(alias="notIn")] = (
        UNSET
    )
    r"""NotIn specifies that this field cannot be equal to one of the specified
    values
    """

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = [
            "const",
            "gt",
            "gte",
            "ignoreEmpty",
            "in",
            "lt",
            "lte",
            "notIn",
        ]
        nullable_fields = ["in", "notIn"]
        null_default_fields = []

        serialized = handler(self)

        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)
            serialized.pop(k, None)

            optional_nullable = k in optional_fields and k in nullable_fields
            is_set = (
                self.__pydantic_fields_set__.intersection({n})
                or k in null_default_fields
            )  # pylint: disable=no-member

            if val is not None and val != UNSET_SENTINEL:
                m[k] = val
            elif val != UNSET_SENTINEL and (
                not k in optional_fields or (optional_nullable and is_set)
            ):
                m[k] = val

        return m
