"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
import pydantic
from pydantic import model_serializer
from sdk.types import BaseModel, Nullable, OptionalNullable, UNSET, UNSET_SENTINEL
from typing import List
from typing_extensions import Annotated, NotRequired, TypedDict


class EntitlementExclusionCriteriaTypedDict(TypedDict):
    r"""The EntitlementExclusionCriteria message."""

    excluded_app_ids: NotRequired[Nullable[List[str]]]
    r"""The excludedAppIds field."""
    excluded_compliance_framework_ids: NotRequired[Nullable[List[str]]]
    r"""The excludedComplianceFrameworkIds field."""
    excluded_resource_type_ids: NotRequired[Nullable[List[str]]]
    r"""The excludedResourceTypeIds field."""
    excluded_risk_level_ids: NotRequired[Nullable[List[str]]]
    r"""The excludedRiskLevelIds field."""


class EntitlementExclusionCriteria(BaseModel):
    r"""The EntitlementExclusionCriteria message."""

    excluded_app_ids: Annotated[
        OptionalNullable[List[str]], pydantic.Field(alias="excludedAppIds")
    ] = UNSET
    r"""The excludedAppIds field."""

    excluded_compliance_framework_ids: Annotated[
        OptionalNullable[List[str]],
        pydantic.Field(alias="excludedComplianceFrameworkIds"),
    ] = UNSET
    r"""The excludedComplianceFrameworkIds field."""

    excluded_resource_type_ids: Annotated[
        OptionalNullable[List[str]], pydantic.Field(alias="excludedResourceTypeIds")
    ] = UNSET
    r"""The excludedResourceTypeIds field."""

    excluded_risk_level_ids: Annotated[
        OptionalNullable[List[str]], pydantic.Field(alias="excludedRiskLevelIds")
    ] = UNSET
    r"""The excludedRiskLevelIds field."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = [
            "excludedAppIds",
            "excludedComplianceFrameworkIds",
            "excludedResourceTypeIds",
            "excludedRiskLevelIds",
        ]
        nullable_fields = [
            "excludedAppIds",
            "excludedComplianceFrameworkIds",
            "excludedResourceTypeIds",
            "excludedRiskLevelIds",
        ]
        null_default_fields = []

        serialized = handler(self)

        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)
            serialized.pop(k, None)

            optional_nullable = k in optional_fields and k in nullable_fields
            is_set = (
                self.__pydantic_fields_set__.intersection({n})
                or k in null_default_fields
            )  # pylint: disable=no-member

            if val is not None and val != UNSET_SENTINEL:
                m[k] = val
            elif val != UNSET_SENTINEL and (
                not k in optional_fields or (optional_nullable and is_set)
            ):
                m[k] = val

        return m
