"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
from .appentitlementuserbinding import AppEntitlementUserBinding
from dataclasses_json import Undefined, dataclass_json
from sdk import utils
from typing import List, Optional


@dataclass_json(undefined=Undefined.EXCLUDE)
@dataclasses.dataclass
class ListAppUsersForIdentityWithGrantResponse:
    r"""The ListAppUsersForIdentityWithGrantResponse message."""
    UNSET='__SPEAKEASY_UNSET__'
    bindings: Optional[List[AppEntitlementUserBinding]] = dataclasses.field(default=UNSET, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('bindings'), 'exclude': lambda f: f is ListAppUsersForIdentityWithGrantResponse.UNSET }})
    r"""The list of app users that may also have grant information."""
    

