"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
from .provisionpolicy import ProvisionPolicy
from dataclasses_json import Undefined, dataclass_json
from sdk import utils
from typing import List, Optional


@dataclass_json(undefined=Undefined.EXCLUDE)
@dataclasses.dataclass
class MultiStep:
    r"""MultiStep indicates that this provision step has multiple steps to process."""
    UNSET='__SPEAKEASY_UNSET__'
    provision_steps: Optional[List[ProvisionPolicy]] = dataclasses.field(default=UNSET, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('provisionSteps'), 'exclude': lambda f: f is MultiStep.UNSET }})
    r"""The array of provision steps to process."""
    

