"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses


@dataclasses.dataclass
class OAuth2AuthorizedAsInput:
    r"""OAuth2AuthorizedAs tracks the user that OAuthed with the connector."""
    

