"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from sdk.types import BaseModel
from typing_extensions import TypedDict


class RemoveAppResourceOwnerResponseTypedDict(TypedDict):
    r"""The RemoveAppResourceOwnerResponse message."""


class RemoveAppResourceOwnerResponse(BaseModel):
    r"""The RemoveAppResourceOwnerResponse message."""
