"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .userref import UserRef, UserRefTypedDict
import pydantic
from pydantic import model_serializer
from sdk.types import BaseModel, Nullable, OptionalNullable, UNSET, UNSET_SENTINEL
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class RemoveFromDelegationTypedDict(TypedDict):
    r"""RemoveFromDelegation: find all users that have the target user as their delegated user, and modify the delegation.

    This message contains a oneof named replacement_user. Only a single field of the following list may be set at a time:
    - replacementUserIdCel
    - replacementUserRef

    """

    user_ref: NotRequired[UserRefTypedDict]
    r"""A reference to a user."""
    user_ref1: NotRequired[UserRefTypedDict]
    r"""A reference to a user."""
    replacement_user_id_cel: NotRequired[Nullable[str]]
    r"""The user who will replace the target user's delegation
    This field is part of the `replacement_user` oneof.
    See the documentation for `c1.api.automations.v1.RemoveFromDelegation` for more details.
    """
    use_subject_user: NotRequired[bool]
    r"""If true, the step will use the subject user of the automation as the subject."""
    user_id_cel: NotRequired[str]
    r"""The userIdCel field."""


class RemoveFromDelegation(BaseModel):
    r"""RemoveFromDelegation: find all users that have the target user as their delegated user, and modify the delegation.

    This message contains a oneof named replacement_user. Only a single field of the following list may be set at a time:
    - replacementUserIdCel
    - replacementUserRef

    """

    user_ref: Annotated[
        Optional[UserRef], pydantic.Field(alias="replacementUserRef")
    ] = None
    r"""A reference to a user."""

    user_ref1: Annotated[Optional[UserRef], pydantic.Field(alias="userRef")] = None
    r"""A reference to a user."""

    replacement_user_id_cel: Annotated[
        OptionalNullable[str], pydantic.Field(alias="replacementUserIdCel")
    ] = UNSET
    r"""The user who will replace the target user's delegation
    This field is part of the `replacement_user` oneof.
    See the documentation for `c1.api.automations.v1.RemoveFromDelegation` for more details.
    """

    use_subject_user: Annotated[
        Optional[bool], pydantic.Field(alias="useSubjectUser")
    ] = None
    r"""If true, the step will use the subject user of the automation as the subject."""

    user_id_cel: Annotated[Optional[str], pydantic.Field(alias="userIdCel")] = None
    r"""The userIdCel field."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = [
            "UserRef",
            "UserRef1",
            "replacementUserIdCel",
            "useSubjectUser",
            "userIdCel",
        ]
        nullable_fields = ["replacementUserIdCel"]
        null_default_fields = []

        serialized = handler(self)

        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)
            serialized.pop(k, None)

            optional_nullable = k in optional_fields and k in nullable_fields
            is_set = (
                self.__pydantic_fields_set__.intersection({n})
                or k in null_default_fields
            )  # pylint: disable=no-member

            if val is not None and val != UNSET_SENTINEL:
                m[k] = val
            elif val != UNSET_SENTINEL and (
                not k in optional_fields or (optional_nullable and is_set)
            ):
                m[k] = val

        return m
