"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
from dataclasses_json import Undefined, dataclass_json
from sdk import utils
from typing import Optional


@dataclass_json(undefined=Undefined.EXCLUDE)

@dataclasses.dataclass
class RequestCatalogExpandMask:
    r"""The RequestCatalogExpandMask includes the paths in the catalog view to expand in the return value of this call."""
    paths: Optional[list[str]] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('paths') }})
    r"""An array of paths to be expanded in the response. May be any combination of \\"*\\", \\"created_by_user_id\\", \\"app_ids\\", and \\"access_entitlements\\"."""
    

