"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from sdk.types import BaseModel
from typing_extensions import TypedDict


class RequestSchemaServiceDeleteResponseTypedDict(TypedDict):
    r"""The RequestSchemaServiceDeleteResponse message."""


class RequestSchemaServiceDeleteResponse(BaseModel):
    r"""The RequestSchemaServiceDeleteResponse message."""
