"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .requestcatalog import RequestCatalog, RequestCatalogTypedDict
import pydantic
from sdk.types import BaseModel
from typing import Optional, TypedDict
from typing_extensions import Annotated, NotRequired


class RequestCatalogViewTypedDict(TypedDict):
    r"""The request catalog view contains the serialized request catalog and paths to objects referenced by the request catalog."""
    
    request_catalog: NotRequired[RequestCatalogTypedDict]
    r"""The RequestCatalog is used for managing which entitlements are requestable, and who can request them."""
    access_entitlements_path: NotRequired[str]
    r"""JSONPATH expression indicating the location of the access entitlement objects, that the request catalog allows users to request, in the array."""
    app_paths: NotRequired[str]
    r"""JSONPATH expression indicating the location of the App object in the array."""
    created_by_user_path: NotRequired[str]
    r"""JSONPATH expression indicating the location of the User object, that created the request catalog, in the array."""
    

class RequestCatalogView(BaseModel):
    r"""The request catalog view contains the serialized request catalog and paths to objects referenced by the request catalog."""
    
    request_catalog: Annotated[Optional[RequestCatalog], pydantic.Field(alias="requestCatalog")] = None
    r"""The RequestCatalog is used for managing which entitlements are requestable, and who can request them."""
    access_entitlements_path: Annotated[Optional[str], pydantic.Field(alias="accessEntitlementsPath")] = None
    r"""JSONPATH expression indicating the location of the access entitlement objects, that the request catalog allows users to request, in the array."""
    app_paths: Annotated[Optional[str], pydantic.Field(alias="appPaths")] = None
    r"""JSONPATH expression indicating the location of the App object in the array."""
    created_by_user_path: Annotated[Optional[str], pydantic.Field(alias="createdByUserPath")] = None
    r"""JSONPATH expression indicating the location of the User object, that created the request catalog, in the array."""
    
