"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from sdk.types import BaseModel
from typing_extensions import TypedDict


class ResumeSyncRequestTypedDict(TypedDict):
    r"""The ResumeSyncRequest message."""


class ResumeSyncRequest(BaseModel):
    r"""The ResumeSyncRequest message."""
