"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from datetime import datetime
import pydantic
from sdk.types import BaseModel
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class ScheduleTriggerTypedDict(TypedDict):
    r"""The ScheduleTrigger message."""

    advanced: NotRequired[bool]
    r"""The advanced field."""
    cron_spec: NotRequired[str]
    r"""The cronSpec field."""
    skip_if_true_cel: NotRequired[str]
    r"""The skipIfTrueCel field."""
    start: NotRequired[datetime]


class ScheduleTrigger(BaseModel):
    r"""The ScheduleTrigger message."""

    advanced: Optional[bool] = None
    r"""The advanced field."""

    cron_spec: Annotated[Optional[str], pydantic.Field(alias="cronSpec")] = None
    r"""The cronSpec field."""

    skip_if_true_cel: Annotated[
        Optional[str], pydantic.Field(alias="skipIfTrueCel")
    ] = None
    r"""The skipIfTrueCel field."""

    start: Optional[datetime] = None
