"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .automationexecutionexpandmask import (
    AutomationExecutionExpandMask,
    AutomationExecutionExpandMaskTypedDict,
)
from .automationexecutionref import (
    AutomationExecutionRef,
    AutomationExecutionRefTypedDict,
)
from enum import Enum
import pydantic
from pydantic import model_serializer
from pydantic.functional_serializers import PlainSerializer
from pydantic.functional_validators import BeforeValidator, PlainValidator
from sdk import utils
from sdk.types import BaseModel, Nullable, OptionalNullable, UNSET, UNSET_SENTINEL
from sdk.utils import serialize_int, validate_int, validate_open_enum
from typing import List, Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class ExecutionStepStates(str, Enum, metaclass=utils.OpenEnumMeta):
    AUTOMATION_EXECUTION_STATE_UNSPECIFIED = "AUTOMATION_EXECUTION_STATE_UNSPECIFIED"
    AUTOMATION_EXECUTION_STATE_PENDING = "AUTOMATION_EXECUTION_STATE_PENDING"
    AUTOMATION_EXECUTION_STATE_CREATING = "AUTOMATION_EXECUTION_STATE_CREATING"
    AUTOMATION_EXECUTION_STATE_GET_STEP = "AUTOMATION_EXECUTION_STATE_GET_STEP"
    AUTOMATION_EXECUTION_STATE_PROCESS_STEP = "AUTOMATION_EXECUTION_STATE_PROCESS_STEP"
    AUTOMATION_EXECUTION_STATE_COMPLETE_STEP = (
        "AUTOMATION_EXECUTION_STATE_COMPLETE_STEP"
    )
    AUTOMATION_EXECUTION_STATE_DONE = "AUTOMATION_EXECUTION_STATE_DONE"
    AUTOMATION_EXECUTION_STATE_ERROR = "AUTOMATION_EXECUTION_STATE_ERROR"
    AUTOMATION_EXECUTION_STATE_TERMINATE = "AUTOMATION_EXECUTION_STATE_TERMINATE"
    AUTOMATION_EXECUTION_STATE_WAITING = "AUTOMATION_EXECUTION_STATE_WAITING"


class SearchAutomationExecutionsRequestTypedDict(TypedDict):
    r"""The SearchAutomationExecutionsRequest message."""

    automation_execution_expand_mask: NotRequired[
        AutomationExecutionExpandMaskTypedDict
    ]
    r"""The AutomationExecutionExpandMask message."""
    automation_template_id: NotRequired[str]
    r"""The automationTemplateId field."""
    execution_id: NotRequired[int]
    r"""The executionId field."""
    execution_step_states: NotRequired[Nullable[List[ExecutionStepStates]]]
    r"""The executionStepStates field."""
    page_size: NotRequired[int]
    r"""The pageSize field."""
    page_token: NotRequired[str]
    r"""The pageToken field."""
    query: NotRequired[str]
    r"""The query field."""
    refs: NotRequired[Nullable[List[AutomationExecutionRefTypedDict]]]
    r"""The refs field."""


class SearchAutomationExecutionsRequest(BaseModel):
    r"""The SearchAutomationExecutionsRequest message."""

    automation_execution_expand_mask: Annotated[
        Optional[AutomationExecutionExpandMask], pydantic.Field(alias="expandMask")
    ] = None
    r"""The AutomationExecutionExpandMask message."""

    automation_template_id: Annotated[
        Optional[str], pydantic.Field(alias="automationTemplateId")
    ] = None
    r"""The automationTemplateId field."""

    execution_id: Annotated[
        Annotated[
            Optional[int],
            BeforeValidator(validate_int),
            PlainSerializer(serialize_int(True)),
        ],
        pydantic.Field(alias="executionId"),
    ] = None
    r"""The executionId field."""

    execution_step_states: Annotated[
        OptionalNullable[
            List[
                Annotated[
                    ExecutionStepStates, PlainValidator(validate_open_enum(False))
                ]
            ]
        ],
        pydantic.Field(alias="executionStepStates"),
    ] = UNSET
    r"""The executionStepStates field."""

    page_size: Annotated[Optional[int], pydantic.Field(alias="pageSize")] = None
    r"""The pageSize field."""

    page_token: Annotated[Optional[str], pydantic.Field(alias="pageToken")] = None
    r"""The pageToken field."""

    query: Optional[str] = None
    r"""The query field."""

    refs: OptionalNullable[List[AutomationExecutionRef]] = UNSET
    r"""The refs field."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = [
            "AutomationExecutionExpandMask",
            "automationTemplateId",
            "executionId",
            "executionStepStates",
            "pageSize",
            "pageToken",
            "query",
            "refs",
        ]
        nullable_fields = ["executionStepStates", "refs"]
        null_default_fields = []

        serialized = handler(self)

        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)
            serialized.pop(k, None)

            optional_nullable = k in optional_fields and k in nullable_fields
            is_set = (
                self.__pydantic_fields_set__.intersection({n})
                or k in null_default_fields
            )  # pylint: disable=no-member

            if val is not None and val != UNSET_SENTINEL:
                m[k] = val
            elif val != UNSET_SENTINEL and (
                not k in optional_fields or (optional_nullable and is_set)
            ):
                m[k] = val

        return m
