"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
import pydantic
from sdk.types import BaseModel
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class TaskAuditPolicyProvisionCancelledTypedDict(TypedDict):
    r"""The TaskAuditPolicyProvisionCancelled message."""

    cancel_reason: NotRequired[str]
    r"""The cancelReason field."""


class TaskAuditPolicyProvisionCancelled(BaseModel):
    r"""The TaskAuditPolicyProvisionCancelled message."""

    cancel_reason: Annotated[Optional[str], pydantic.Field(alias="cancelReason")] = None
    r"""The cancelReason field."""
