"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
import pydantic
from sdk.types import BaseModel
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class TaskAuditRestartTypedDict(TypedDict):
    r"""The TaskAuditRestart message."""

    old_policy_step_id: NotRequired[str]
    r"""The oldPolicyStepId field."""


class TaskAuditRestart(BaseModel):
    r"""The TaskAuditRestart message."""

    old_policy_step_id: Annotated[
        Optional[str], pydantic.Field(alias="oldPolicyStepId")
    ] = None
    r"""The oldPolicyStepId field."""
