"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
import pydantic
from sdk.types import BaseModel
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class TestStepUpProviderResponseTypedDict(TypedDict):
    r"""The TestStepUpProviderResponse message."""

    __test__ = False  # pyright: ignore[reportGeneralTypeIssues]

    redirect_url: NotRequired[str]
    r"""The URL to redirect the user to for testing the Step Up flow"""


class TestStepUpProviderResponse(BaseModel):
    r"""The TestStepUpProviderResponse message."""

    __test__ = False

    redirect_url: Annotated[Optional[str], pydantic.Field(alias="redirectUrl")] = None
    r"""The URL to redirect the user to for testing the Step Up flow"""
