"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from sdk.types import BaseModel
from typing_extensions import TypedDict


class TestStepUpProviderRequestTypedDict(TypedDict):
    r"""The TestStepUpProviderRequest message."""

    __test__ = False  # pyright: ignore[reportGeneralTypeIssues]


class TestStepUpProviderRequest(BaseModel):
    r"""The TestStepUpProviderRequest message."""

    __test__ = False
