"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .vault import Vault, VaultTypedDict
from sdk.types import BaseModel
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class VaultServiceGetResponseTypedDict(TypedDict):
    r"""The VaultServiceGetResponse message."""

    vault: NotRequired[VaultTypedDict]
    r"""The Vault message.

    This message contains a oneof named vault. Only a single field of the following list may be set at a time:
    - groupAuthzVault
    - magicVault

    """


class VaultServiceGetResponse(BaseModel):
    r"""The VaultServiceGetResponse message."""

    vault: Optional[Vault] = None
    r"""The Vault message.

    This message contains a oneof named vault. Only a single field of the following list may be set at a time:
    - groupAuthzVault
    - magicVault

    """
