"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
import httpx
from sdk.models.shared import (
    addautomationexclusionrequest as shared_addautomationexclusionrequest,
    addautomationexclusionresponse as shared_addautomationexclusionresponse,
)
from sdk.types import BaseModel
from sdk.utils import FieldMetadata, PathParamMetadata, RequestMetadata
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class C1APIAppV1AppEntitlementsAddAutomationExclusionRequestTypedDict(TypedDict):
    add_automation_exclusion_request: (
        shared_addautomationexclusionrequest.AddAutomationExclusionRequestTypedDict
    )
    app_entitlement_id: str
    app_id: str


class C1APIAppV1AppEntitlementsAddAutomationExclusionRequest(BaseModel):
    add_automation_exclusion_request: Annotated[
        shared_addautomationexclusionrequest.AddAutomationExclusionRequest,
        FieldMetadata(request=RequestMetadata(media_type="application/json")),
    ]

    app_entitlement_id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]

    app_id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]


class C1APIAppV1AppEntitlementsAddAutomationExclusionResponseTypedDict(TypedDict):
    content_type: str
    r"""HTTP response content type for this operation"""
    status_code: int
    r"""HTTP response status code for this operation"""
    raw_response: httpx.Response
    r"""Raw HTTP response; suitable for custom response parsing"""
    add_automation_exclusion_response: NotRequired[
        shared_addautomationexclusionresponse.AddAutomationExclusionResponseTypedDict
    ]
    r"""Empty response with a status code indicating success."""


class C1APIAppV1AppEntitlementsAddAutomationExclusionResponse(BaseModel):
    content_type: str
    r"""HTTP response content type for this operation"""

    status_code: int
    r"""HTTP response status code for this operation"""

    raw_response: httpx.Response
    r"""Raw HTTP response; suitable for custom response parsing"""

    add_automation_exclusion_response: Optional[
        shared_addautomationexclusionresponse.AddAutomationExclusionResponse
    ] = None
    r"""Empty response with a status code indicating success."""
