"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
import httpx
from sdk.models.shared import requestcatalogmanagementservicegetresponse as shared_requestcatalogmanagementservicegetresponse, requestcatalogmanagementserviceupdaterequest as shared_requestcatalogmanagementserviceupdaterequest
from sdk.types import BaseModel
from sdk.utils import FieldMetadata, PathParamMetadata, RequestMetadata
from typing import Optional, TypedDict
from typing_extensions import Annotated, NotRequired


class C1APIRequestcatalogV1RequestCatalogManagementServiceUpdateRequestTypedDict(TypedDict):
    id: str
    request_catalog_management_service_update_request: NotRequired[shared_requestcatalogmanagementserviceupdaterequest.RequestCatalogManagementServiceUpdateRequestTypedDict]
    

class C1APIRequestcatalogV1RequestCatalogManagementServiceUpdateRequest(BaseModel):
    id: Annotated[str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))]
    request_catalog_management_service_update_request: Annotated[Optional[shared_requestcatalogmanagementserviceupdaterequest.RequestCatalogManagementServiceUpdateRequest], FieldMetadata(request=RequestMetadata(media_type="application/json"))] = None
    

class C1APIRequestcatalogV1RequestCatalogManagementServiceUpdateResponseTypedDict(TypedDict):
    content_type: str
    r"""HTTP response content type for this operation"""
    status_code: int
    r"""HTTP response status code for this operation"""
    raw_response: httpx.Response
    r"""Raw HTTP response; suitable for custom response parsing"""
    request_catalog_management_service_get_response: NotRequired[shared_requestcatalogmanagementservicegetresponse.RequestCatalogManagementServiceGetResponseTypedDict]
    r"""The request catalog management service get response returns a request catalog view with the expanded items in the expanded array indicated by the expand mask in the request."""
    

class C1APIRequestcatalogV1RequestCatalogManagementServiceUpdateResponse(BaseModel):
    content_type: str
    r"""HTTP response content type for this operation"""
    status_code: int
    r"""HTTP response status code for this operation"""
    raw_response: httpx.Response
    r"""Raw HTTP response; suitable for custom response parsing"""
    request_catalog_management_service_get_response: Optional[shared_requestcatalogmanagementservicegetresponse.RequestCatalogManagementServiceGetResponse] = None
    r"""The request catalog management service get response returns a request catalog view with the expanded items in the expanded array indicated by the expand mask in the request."""
    
