"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
import httpx
from sdk.models.shared import (
    connectorservicecreaterequest as shared_connectorservicecreaterequest,
    connectorservicecreateresponse as shared_connectorservicecreateresponse,
)
from sdk.types import BaseModel
from sdk.utils import FieldMetadata, PathParamMetadata, RequestMetadata
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class C1APIAppV1ConnectorServiceCreateRequestTypedDict(TypedDict):
    connector_service_create_request: (
        shared_connectorservicecreaterequest.ConnectorServiceCreateRequestTypedDict
    )
    app_id: str


class C1APIAppV1ConnectorServiceCreateRequest(BaseModel):
    connector_service_create_request: Annotated[
        shared_connectorservicecreaterequest.ConnectorServiceCreateRequest,
        FieldMetadata(request=RequestMetadata(media_type="application/json")),
    ]

    app_id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]


class C1APIAppV1ConnectorServiceCreateResponseTypedDict(TypedDict):
    content_type: str
    r"""HTTP response content type for this operation"""
    status_code: int
    r"""HTTP response status code for this operation"""
    raw_response: httpx.Response
    r"""Raw HTTP response; suitable for custom response parsing"""
    connector_service_create_response: NotRequired[
        shared_connectorservicecreateresponse.ConnectorServiceCreateResponseTypedDict
    ]
    r"""The ConnectorServiceCreateResponse is the response returned from creating a connector."""


class C1APIAppV1ConnectorServiceCreateResponse(BaseModel):
    content_type: str
    r"""HTTP response content type for this operation"""

    status_code: int
    r"""HTTP response status code for this operation"""

    raw_response: httpx.Response
    r"""Raw HTTP response; suitable for custom response parsing"""

    connector_service_create_response: Optional[
        shared_connectorservicecreateresponse.ConnectorServiceCreateResponse
    ] = None
    r"""The ConnectorServiceCreateResponse is the response returned from creating a connector."""
