"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
import httpx
from sdk.models.shared import (
    requestcatalogmanagementserviceupdateappentitlementsrequest as shared_requestcatalogmanagementserviceupdateappentitlementsrequest,
    requestcatalogmanagementserviceupdateappentitlementsresponse as shared_requestcatalogmanagementserviceupdateappentitlementsresponse,
)
from sdk.types import BaseModel
from sdk.utils import FieldMetadata, PathParamMetadata, RequestMetadata
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class C1APIRequestcatalogV1RequestCatalogManagementServiceUpdateAppEntitlementsRequestTypedDict(
    TypedDict
):
    request_catalog_management_service_update_app_entitlements_request: shared_requestcatalogmanagementserviceupdateappentitlementsrequest.RequestCatalogManagementServiceUpdateAppEntitlementsRequestTypedDict
    catalog_id: str


class C1APIRequestcatalogV1RequestCatalogManagementServiceUpdateAppEntitlementsRequest(
    BaseModel
):
    request_catalog_management_service_update_app_entitlements_request: Annotated[
        shared_requestcatalogmanagementserviceupdateappentitlementsrequest.RequestCatalogManagementServiceUpdateAppEntitlementsRequest,
        FieldMetadata(request=RequestMetadata(media_type="application/json")),
    ]

    catalog_id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]


class C1APIRequestcatalogV1RequestCatalogManagementServiceUpdateAppEntitlementsResponseTypedDict(
    TypedDict
):
    content_type: str
    r"""HTTP response content type for this operation"""
    status_code: int
    r"""HTTP response status code for this operation"""
    raw_response: httpx.Response
    r"""Raw HTTP response; suitable for custom response parsing"""
    request_catalog_management_service_update_app_entitlements_response: NotRequired[
        shared_requestcatalogmanagementserviceupdateappentitlementsresponse.RequestCatalogManagementServiceUpdateAppEntitlementsResponseTypedDict
    ]
    r"""The RequestCatalogManagementServiceUpdateAppEntitlementsResponse object is is the response from UpdateAppEntitlements endpoint."""


class C1APIRequestcatalogV1RequestCatalogManagementServiceUpdateAppEntitlementsResponse(
    BaseModel
):
    content_type: str
    r"""HTTP response content type for this operation"""

    status_code: int
    r"""HTTP response status code for this operation"""

    raw_response: httpx.Response
    r"""Raw HTTP response; suitable for custom response parsing"""

    request_catalog_management_service_update_app_entitlements_response: Optional[
        shared_requestcatalogmanagementserviceupdateappentitlementsresponse.RequestCatalogManagementServiceUpdateAppEntitlementsResponse
    ] = None
    r"""The RequestCatalogManagementServiceUpdateAppEntitlementsResponse object is is the response from UpdateAppEntitlements endpoint."""
