"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
import httpx
from sdk.models.shared import (
    createstepupproviderresponse as shared_createstepupproviderresponse,
)
from sdk.types import BaseModel
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class C1APIStepupV1StepUpProviderServiceCreateResponseTypedDict(TypedDict):
    content_type: str
    r"""HTTP response content type for this operation"""
    status_code: int
    r"""HTTP response status code for this operation"""
    raw_response: httpx.Response
    r"""Raw HTTP response; suitable for custom response parsing"""
    create_step_up_provider_response: NotRequired[
        shared_createstepupproviderresponse.CreateStepUpProviderResponseTypedDict
    ]
    r"""Successful response"""


class C1APIStepupV1StepUpProviderServiceCreateResponse(BaseModel):
    content_type: str
    r"""HTTP response content type for this operation"""

    status_code: int
    r"""HTTP response status code for this operation"""

    raw_response: httpx.Response
    r"""Raw HTTP response; suitable for custom response parsing"""

    create_step_up_provider_response: Optional[
        shared_createstepupproviderresponse.CreateStepUpProviderResponse
    ] = None
    r"""Successful response"""
