"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
import requests as requests_http
from ...models.shared import webhooksservicegetresponse as shared_webhooksservicegetresponse
from typing import Optional


@dataclasses.dataclass
class C1APIWebhooksV1WebhooksServiceGetRequest:
    id: str = dataclasses.field(metadata={'path_param': { 'field_name': 'id', 'style': 'simple', 'explode': False }})
    



@dataclasses.dataclass
class C1APIWebhooksV1WebhooksServiceGetResponse:
    content_type: str = dataclasses.field()
    r"""HTTP response content type for this operation"""
    status_code: int = dataclasses.field()
    r"""HTTP response status code for this operation"""
    raw_response: requests_http.Response = dataclasses.field()
    r"""Raw HTTP response; suitable for custom response parsing"""
    webhooks_service_get_response: Optional[shared_webhooksservicegetresponse.WebhooksServiceGetResponse] = dataclasses.field(default=None)
    r"""Successful response"""
    

