"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
import httpx
from sdk.models.shared import searchpoliciesresponse as shared_searchpoliciesresponse
from sdk.types import BaseModel
from typing import Callable, Optional
from typing_extensions import NotRequired, TypedDict


class C1APIPolicyV1PolicySearchSearchResponseTypedDict(TypedDict):
    content_type: str
    r"""HTTP response content type for this operation"""
    status_code: int
    r"""HTTP response status code for this operation"""
    raw_response: httpx.Response
    r"""Raw HTTP response; suitable for custom response parsing"""
    search_policies_response: NotRequired[
        shared_searchpoliciesresponse.SearchPoliciesResponseTypedDict
    ]
    r"""Successful response"""


class C1APIPolicyV1PolicySearchSearchResponse(BaseModel):
    next: Callable[[], Optional[C1APIPolicyV1PolicySearchSearchResponse]]

    content_type: str
    r"""HTTP response content type for this operation"""

    status_code: int
    r"""HTTP response status code for this operation"""

    raw_response: httpx.Response
    r"""Raw HTTP response; suitable for custom response parsing"""

    search_policies_response: Optional[
        shared_searchpoliciesresponse.SearchPoliciesResponse
    ] = None
    r"""Successful response"""
