"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
import httpx
from sdk.models.shared import (
    webhooksserviceupdaterequest as shared_webhooksserviceupdaterequest,
    webhooksserviceupdateresponse as shared_webhooksserviceupdateresponse,
)
from sdk.types import BaseModel
from sdk.utils import FieldMetadata, PathParamMetadata, RequestMetadata
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class C1APIWebhooksV1WebhooksServiceUpdateRequestTypedDict(TypedDict):
    webhooks_service_update_request: (
        shared_webhooksserviceupdaterequest.WebhooksServiceUpdateRequestTypedDict
    )
    id: str


class C1APIWebhooksV1WebhooksServiceUpdateRequest(BaseModel):
    webhooks_service_update_request: Annotated[
        shared_webhooksserviceupdaterequest.WebhooksServiceUpdateRequest,
        FieldMetadata(request=RequestMetadata(media_type="application/json")),
    ]

    id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]


class C1APIWebhooksV1WebhooksServiceUpdateResponseTypedDict(TypedDict):
    content_type: str
    r"""HTTP response content type for this operation"""
    status_code: int
    r"""HTTP response status code for this operation"""
    raw_response: httpx.Response
    r"""Raw HTTP response; suitable for custom response parsing"""
    webhooks_service_update_response: NotRequired[
        shared_webhooksserviceupdateresponse.WebhooksServiceUpdateResponseTypedDict
    ]
    r"""Successful response"""


class C1APIWebhooksV1WebhooksServiceUpdateResponse(BaseModel):
    content_type: str
    r"""HTTP response content type for this operation"""

    status_code: int
    r"""HTTP response status code for this operation"""

    raw_response: httpx.Response
    r"""Raw HTTP response; suitable for custom response parsing"""

    webhooks_service_update_response: Optional[
        shared_webhooksserviceupdateresponse.WebhooksServiceUpdateResponse
    ] = None
    r"""Successful response"""
