"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
import httpx
from sdk.models.shared import (
    deleteappentitlementownersrequest as shared_deleteappentitlementownersrequest,
    deleteappentitlementownersresponse as shared_deleteappentitlementownersresponse,
)
from sdk.types import BaseModel
from sdk.utils import FieldMetadata, PathParamMetadata, RequestMetadata
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class C1APIAppV1AppEntitlementOwnersDeleteRequestTypedDict(TypedDict):
    app_id: str
    entitlement_id: str
    delete_app_entitlement_owners_request: NotRequired[
        shared_deleteappentitlementownersrequest.DeleteAppEntitlementOwnersRequestTypedDict
    ]


class C1APIAppV1AppEntitlementOwnersDeleteRequest(BaseModel):
    app_id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]

    entitlement_id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]

    delete_app_entitlement_owners_request: Annotated[
        Optional[
            shared_deleteappentitlementownersrequest.DeleteAppEntitlementOwnersRequest
        ],
        FieldMetadata(request=RequestMetadata(media_type="application/json")),
    ] = None


class C1APIAppV1AppEntitlementOwnersDeleteResponseTypedDict(TypedDict):
    content_type: str
    r"""HTTP response content type for this operation"""
    status_code: int
    r"""HTTP response status code for this operation"""
    raw_response: httpx.Response
    r"""Raw HTTP response; suitable for custom response parsing"""
    delete_app_entitlement_owners_response: NotRequired[
        shared_deleteappentitlementownersresponse.DeleteAppEntitlementOwnersResponseTypedDict
    ]
    r"""the empty response message for deleting app entitlement owners."""


class C1APIAppV1AppEntitlementOwnersDeleteResponse(BaseModel):
    content_type: str
    r"""HTTP response content type for this operation"""

    status_code: int
    r"""HTTP response status code for this operation"""

    raw_response: httpx.Response
    r"""Raw HTTP response; suitable for custom response parsing"""

    delete_app_entitlement_owners_response: Optional[
        shared_deleteappentitlementownersresponse.DeleteAppEntitlementOwnersResponse
    ] = None
    r"""the empty response message for deleting app entitlement owners."""
