"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
import httpx
from sdk.models.shared import (
    updatemanuallymanagedresourcetyperequest as shared_updatemanuallymanagedresourcetyperequest,
    updatemanuallymanagedresourcetyperesponse as shared_updatemanuallymanagedresourcetyperesponse,
)
from sdk.types import BaseModel
from sdk.utils import FieldMetadata, PathParamMetadata, RequestMetadata
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class C1APIAppV1AppResourceTypeServiceUpdateManuallyManagedResourceTypeRequestTypedDict(
    TypedDict
):
    app_id: str
    id: str
    update_manually_managed_resource_type_request: NotRequired[
        shared_updatemanuallymanagedresourcetyperequest.UpdateManuallyManagedResourceTypeRequestTypedDict
    ]


class C1APIAppV1AppResourceTypeServiceUpdateManuallyManagedResourceTypeRequest(
    BaseModel
):
    app_id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]

    id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]

    update_manually_managed_resource_type_request: Annotated[
        Optional[
            shared_updatemanuallymanagedresourcetyperequest.UpdateManuallyManagedResourceTypeRequest
        ],
        FieldMetadata(request=RequestMetadata(media_type="application/json")),
    ] = None


class C1APIAppV1AppResourceTypeServiceUpdateManuallyManagedResourceTypeResponseTypedDict(
    TypedDict
):
    content_type: str
    r"""HTTP response content type for this operation"""
    status_code: int
    r"""HTTP response status code for this operation"""
    raw_response: httpx.Response
    r"""Raw HTTP response; suitable for custom response parsing"""
    update_manually_managed_resource_type_response: NotRequired[
        shared_updatemanuallymanagedresourcetyperesponse.UpdateManuallyManagedResourceTypeResponseTypedDict
    ]
    r"""Successful response"""


class C1APIAppV1AppResourceTypeServiceUpdateManuallyManagedResourceTypeResponse(
    BaseModel
):
    content_type: str
    r"""HTTP response content type for this operation"""

    status_code: int
    r"""HTTP response status code for this operation"""

    raw_response: httpx.Response
    r"""Raw HTTP response; suitable for custom response parsing"""

    update_manually_managed_resource_type_response: Optional[
        shared_updatemanuallymanagedresourcetyperesponse.UpdateManuallyManagedResourceTypeResponse
    ] = None
    r"""Successful response"""
