"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
import requests as requests_http
from ...models.shared import addappentitlementownerrequest as shared_addappentitlementownerrequest
from ...models.shared import addappentitlementownerresponse as shared_addappentitlementownerresponse
from typing import Optional


@dataclasses.dataclass
class C1APIAppV1AppEntitlementOwnersAddRequest:
    app_id: str = dataclasses.field(metadata={'path_param': { 'field_name': 'app_id', 'style': 'simple', 'explode': False }})
    entitlement_id: str = dataclasses.field(metadata={'path_param': { 'field_name': 'entitlement_id', 'style': 'simple', 'explode': False }})
    add_app_entitlement_owner_request: Optional[shared_addappentitlementownerrequest.AddAppEntitlementOwnerRequest] = dataclasses.field(default=None, metadata={'request': { 'media_type': 'application/json' }})
    



@dataclasses.dataclass
class C1APIAppV1AppEntitlementOwnersAddResponse:
    content_type: str = dataclasses.field()
    r"""HTTP response content type for this operation"""
    status_code: int = dataclasses.field()
    r"""HTTP response status code for this operation"""
    raw_response: requests_http.Response = dataclasses.field()
    r"""Raw HTTP response; suitable for custom response parsing"""
    add_app_entitlement_owner_response: Optional[shared_addappentitlementownerresponse.AddAppEntitlementOwnerResponse] = dataclasses.field(default=None)
    r"""The empty response message for adding an app entitlement owner."""
    

