"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
import httpx
from sdk.models.shared import (
    requestschemaservicecreateentitlementbindingresponse as shared_requestschemaservicecreateentitlementbindingresponse,
)
from sdk.types import BaseModel
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class C1APIRequestSchemaV1RequestSchemaServiceCreateEntitlementBindingResponseTypedDict(
    TypedDict
):
    content_type: str
    r"""HTTP response content type for this operation"""
    status_code: int
    r"""HTTP response status code for this operation"""
    raw_response: httpx.Response
    r"""Raw HTTP response; suitable for custom response parsing"""
    request_schema_service_create_entitlement_binding_response: NotRequired[
        shared_requestschemaservicecreateentitlementbindingresponse.RequestSchemaServiceCreateEntitlementBindingResponseTypedDict
    ]
    r"""Successful response"""


class C1APIRequestSchemaV1RequestSchemaServiceCreateEntitlementBindingResponse(
    BaseModel
):
    content_type: str
    r"""HTTP response content type for this operation"""

    status_code: int
    r"""HTTP response status code for this operation"""

    raw_response: httpx.Response
    r"""Raw HTTP response; suitable for custom response parsing"""

    request_schema_service_create_entitlement_binding_response: Optional[
        shared_requestschemaservicecreateentitlementbindingresponse.RequestSchemaServiceCreateEntitlementBindingResponse
    ] = None
    r"""Successful response"""
