"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
import httpx
from sdk.models.shared import directoryservicelistresponse as shared_directoryservicelistresponse
from sdk.types import BaseModel
from sdk.utils import FieldMetadata, QueryParamMetadata
from typing import Optional, TypedDict
from typing_extensions import Annotated, NotRequired


class C1APIDirectoryV1DirectoryServiceListRequestTypedDict(TypedDict):
    page_size: NotRequired[int]
    page_token: NotRequired[str]
    

class C1APIDirectoryV1DirectoryServiceListRequest(BaseModel):
    page_size: Annotated[Optional[int], FieldMetadata(query=QueryParamMetadata(style="form", explode=True))] = None
    page_token: Annotated[Optional[str], FieldMetadata(query=QueryParamMetadata(style="form", explode=True))] = None
    

class C1APIDirectoryV1DirectoryServiceListResponseTypedDict(TypedDict):
    content_type: str
    r"""HTTP response content type for this operation"""
    status_code: int
    r"""HTTP response status code for this operation"""
    raw_response: httpx.Response
    r"""Raw HTTP response; suitable for custom response parsing"""
    directory_service_list_response: NotRequired[shared_directoryservicelistresponse.DirectoryServiceListResponseTypedDict]
    r"""The DirectoryServiceListResponse message contains a list of results and a nextPageToken if applicable."""
    

class C1APIDirectoryV1DirectoryServiceListResponse(BaseModel):
    content_type: str
    r"""HTTP response content type for this operation"""
    status_code: int
    r"""HTTP response status code for this operation"""
    raw_response: httpx.Response
    r"""Raw HTTP response; suitable for custom response parsing"""
    directory_service_list_response: Optional[shared_directoryservicelistresponse.DirectoryServiceListResponse] = None
    r"""The DirectoryServiceListResponse message contains a list of results and a nextPageToken if applicable."""
    
