"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
import httpx
from sdk.models.shared import (
    requestcatalogmanagementservicedeleterequest as shared_requestcatalogmanagementservicedeleterequest,
    requestcatalogmanagementservicedeleteresponse as shared_requestcatalogmanagementservicedeleteresponse,
)
from sdk.types import BaseModel
from sdk.utils import FieldMetadata, PathParamMetadata, RequestMetadata
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class C1APIRequestcatalogV1RequestCatalogManagementServiceDeleteRequestTypedDict(
    TypedDict
):
    request_catalog_management_service_delete_request: shared_requestcatalogmanagementservicedeleterequest.RequestCatalogManagementServiceDeleteRequestTypedDict
    id: str


class C1APIRequestcatalogV1RequestCatalogManagementServiceDeleteRequest(BaseModel):
    request_catalog_management_service_delete_request: Annotated[
        shared_requestcatalogmanagementservicedeleterequest.RequestCatalogManagementServiceDeleteRequest,
        FieldMetadata(request=RequestMetadata(media_type="application/json")),
    ]

    id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]


class C1APIRequestcatalogV1RequestCatalogManagementServiceDeleteResponseTypedDict(
    TypedDict
):
    content_type: str
    r"""HTTP response content type for this operation"""
    status_code: int
    r"""HTTP response status code for this operation"""
    raw_response: httpx.Response
    r"""Raw HTTP response; suitable for custom response parsing"""
    request_catalog_management_service_delete_response: NotRequired[
        shared_requestcatalogmanagementservicedeleteresponse.RequestCatalogManagementServiceDeleteResponseTypedDict
    ]
    r"""Empty response with a status code indicating success."""


class C1APIRequestcatalogV1RequestCatalogManagementServiceDeleteResponse(BaseModel):
    content_type: str
    r"""HTTP response content type for this operation"""

    status_code: int
    r"""HTTP response status code for this operation"""

    raw_response: httpx.Response
    r"""Raw HTTP response; suitable for custom response parsing"""

    request_catalog_management_service_delete_response: Optional[
        shared_requestcatalogmanagementservicedeleteresponse.RequestCatalogManagementServiceDeleteResponse
    ] = None
    r"""Empty response with a status code indicating success."""
