"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
import httpx
from sdk.models.shared import (
    functionsservicelistcommitsresponse as shared_functionsservicelistcommitsresponse,
)
from sdk.types import BaseModel
from sdk.utils import FieldMetadata, PathParamMetadata
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class C1APIFunctionsV1FunctionsServiceListCommitsRequestTypedDict(TypedDict):
    function_id: str


class C1APIFunctionsV1FunctionsServiceListCommitsRequest(BaseModel):
    function_id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]


class C1APIFunctionsV1FunctionsServiceListCommitsResponseTypedDict(TypedDict):
    content_type: str
    r"""HTTP response content type for this operation"""
    status_code: int
    r"""HTTP response status code for this operation"""
    raw_response: httpx.Response
    r"""Raw HTTP response; suitable for custom response parsing"""
    functions_service_list_commits_response: NotRequired[
        shared_functionsservicelistcommitsresponse.FunctionsServiceListCommitsResponseTypedDict
    ]
    r"""Successful response"""


class C1APIFunctionsV1FunctionsServiceListCommitsResponse(BaseModel):
    content_type: str
    r"""HTTP response content type for this operation"""

    status_code: int
    r"""HTTP response status code for this operation"""

    raw_response: httpx.Response
    r"""Raw HTTP response; suitable for custom response parsing"""

    functions_service_list_commits_response: Optional[
        shared_functionsservicelistcommitsresponse.FunctionsServiceListCommitsResponse
    ] = None
    r"""Successful response"""
