"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
import httpx
from sdk.models.shared import (
    taskactionsservicehardresetrequest as shared_taskactionsservicehardresetrequest,
    taskactionsservicehardresetresponse as shared_taskactionsservicehardresetresponse,
)
from sdk.types import BaseModel
from sdk.utils import FieldMetadata, PathParamMetadata, RequestMetadata
from typing import Optional, TypedDict
from typing_extensions import Annotated, NotRequired


class C1APITaskV1TaskActionsServiceHardResetRequestTypedDict(TypedDict):
    task_id: str
    task_actions_service_hard_reset_request: NotRequired[
        shared_taskactionsservicehardresetrequest.TaskActionsServiceHardResetRequestTypedDict
    ]


class C1APITaskV1TaskActionsServiceHardResetRequest(BaseModel):
    task_id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]

    task_actions_service_hard_reset_request: Annotated[
        Optional[
            shared_taskactionsservicehardresetrequest.TaskActionsServiceHardResetRequest
        ],
        FieldMetadata(request=RequestMetadata(media_type="application/json")),
    ] = None


class C1APITaskV1TaskActionsServiceHardResetResponseTypedDict(TypedDict):
    content_type: str
    r"""HTTP response content type for this operation"""
    status_code: int
    r"""HTTP response status code for this operation"""
    raw_response: httpx.Response
    r"""Raw HTTP response; suitable for custom response parsing"""
    task_actions_service_hard_reset_response: NotRequired[
        shared_taskactionsservicehardresetresponse.TaskActionsServiceHardResetResponseTypedDict
    ]
    r"""Successful response"""


class C1APITaskV1TaskActionsServiceHardResetResponse(BaseModel):
    content_type: str
    r"""HTTP response content type for this operation"""

    status_code: int
    r"""HTTP response status code for this operation"""

    raw_response: httpx.Response
    r"""Raw HTTP response; suitable for custom response parsing"""

    task_actions_service_hard_reset_response: Optional[
        shared_taskactionsservicehardresetresponse.TaskActionsServiceHardResetResponse
    ] = None
    r"""Successful response"""
