"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
import requests as requests_http
from ...models.shared import taskactionsservicecommentrequest as shared_taskactionsservicecommentrequest
from ...models.shared import taskactionsservicecommentresponse as shared_taskactionsservicecommentresponse
from typing import Optional


@dataclasses.dataclass
class C1APITaskV1TaskActionsServiceCommentRequest:
    task_id: str = dataclasses.field(metadata={'path_param': { 'field_name': 'task_id', 'style': 'simple', 'explode': False }})
    task_actions_service_comment_request: Optional[shared_taskactionsservicecommentrequest.TaskActionsServiceCommentRequest] = dataclasses.field(default=None, metadata={'request': { 'media_type': 'application/json' }})
    



@dataclasses.dataclass
class C1APITaskV1TaskActionsServiceCommentResponse:
    content_type: str = dataclasses.field()
    r"""HTTP response content type for this operation"""
    raw_response: requests_http.Response = dataclasses.field()
    r"""Raw HTTP response; suitable for custom response parsing"""
    status_code: int = dataclasses.field()
    r"""HTTP response status code for this operation"""
    task_actions_service_comment_response: Optional[shared_taskactionsservicecommentresponse.TaskActionsServiceCommentResponse] = dataclasses.field(default=None)
    r"""Task actions service comment response returns the task view inluding the expanded array of items that are indicated by the expand mask on the request."""
    

