"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
import httpx
from sdk.models.shared import (
    deleteappentitlementproxyrequest as shared_deleteappentitlementproxyrequest,
    deleteappentitlementproxyresponse as shared_deleteappentitlementproxyresponse,
)
from sdk.types import BaseModel
from sdk.utils import FieldMetadata, PathParamMetadata, RequestMetadata
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class C1APIAppV1AppEntitlementsProxyDeleteRequestTypedDict(TypedDict):
    dst_app_entitlement_id: str
    dst_app_id: str
    src_app_entitlement_id: str
    src_app_id: str
    delete_app_entitlement_proxy_request: NotRequired[
        shared_deleteappentitlementproxyrequest.DeleteAppEntitlementProxyRequestTypedDict
    ]


class C1APIAppV1AppEntitlementsProxyDeleteRequest(BaseModel):
    dst_app_entitlement_id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]

    dst_app_id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]

    src_app_entitlement_id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]

    src_app_id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]

    delete_app_entitlement_proxy_request: Annotated[
        Optional[
            shared_deleteappentitlementproxyrequest.DeleteAppEntitlementProxyRequest
        ],
        FieldMetadata(request=RequestMetadata(media_type="application/json")),
    ] = None


class C1APIAppV1AppEntitlementsProxyDeleteResponseTypedDict(TypedDict):
    content_type: str
    r"""HTTP response content type for this operation"""
    status_code: int
    r"""HTTP response status code for this operation"""
    raw_response: httpx.Response
    r"""Raw HTTP response; suitable for custom response parsing"""
    delete_app_entitlement_proxy_response: NotRequired[
        shared_deleteappentitlementproxyresponse.DeleteAppEntitlementProxyResponseTypedDict
    ]
    r"""Successful response"""


class C1APIAppV1AppEntitlementsProxyDeleteResponse(BaseModel):
    content_type: str
    r"""HTTP response content type for this operation"""

    status_code: int
    r"""HTTP response status code for this operation"""

    raw_response: httpx.Response
    r"""Raw HTTP response; suitable for custom response parsing"""

    delete_app_entitlement_proxy_response: Optional[
        shared_deleteappentitlementproxyresponse.DeleteAppEntitlementProxyResponse
    ] = None
    r"""Successful response"""
