"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
import httpx
from sdk.models.shared import (
    connectorservicedeleterequest as shared_connectorservicedeleterequest,
    connectorservicedeleteresponse as shared_connectorservicedeleteresponse,
)
from sdk.types import BaseModel
from sdk.utils import FieldMetadata, PathParamMetadata, RequestMetadata
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class C1APIAppV1ConnectorServiceDeleteRequestTypedDict(TypedDict):
    connector_service_delete_request: (
        shared_connectorservicedeleterequest.ConnectorServiceDeleteRequestTypedDict
    )
    app_id: str
    id: str


class C1APIAppV1ConnectorServiceDeleteRequest(BaseModel):
    connector_service_delete_request: Annotated[
        shared_connectorservicedeleterequest.ConnectorServiceDeleteRequest,
        FieldMetadata(request=RequestMetadata(media_type="application/json")),
    ]

    app_id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]

    id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]


class C1APIAppV1ConnectorServiceDeleteResponseTypedDict(TypedDict):
    content_type: str
    r"""HTTP response content type for this operation"""
    status_code: int
    r"""HTTP response status code for this operation"""
    raw_response: httpx.Response
    r"""Raw HTTP response; suitable for custom response parsing"""
    connector_service_delete_response: NotRequired[
        shared_connectorservicedeleteresponse.ConnectorServiceDeleteResponseTypedDict
    ]
    r"""Empty response body. Status code indicates success."""


class C1APIAppV1ConnectorServiceDeleteResponse(BaseModel):
    content_type: str
    r"""HTTP response content type for this operation"""

    status_code: int
    r"""HTTP response status code for this operation"""

    raw_response: httpx.Response
    r"""Raw HTTP response; suitable for custom response parsing"""

    connector_service_delete_response: Optional[
        shared_connectorservicedeleteresponse.ConnectorServiceDeleteResponse
    ] = None
    r"""Empty response body. Status code indicates success."""
