"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
import requests as requests_http
from ...models.shared import taskservicecreategrantresponse as shared_taskservicecreategrantresponse
from typing import Optional


@dataclasses.dataclass
class C1APITaskV1TaskServiceCreateGrantTaskResponse:
    content_type: str = dataclasses.field()
    r"""HTTP response content type for this operation"""
    raw_response: requests_http.Response = dataclasses.field()
    r"""Raw HTTP response; suitable for custom response parsing"""
    status_code: int = dataclasses.field()
    r"""HTTP response status code for this operation"""
    task_service_create_grant_response: Optional[shared_taskservicecreategrantresponse.TaskServiceCreateGrantResponse] = dataclasses.field(default=None)
    r"""The TaskServiceCreateGrantResponse returns a task view which has a task including JSONPATHs to the expanded items in the expanded array."""
    

