"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
import httpx
from sdk.models.shared import removeappownerrequest as shared_removeappownerrequest, removeappownerresponse as shared_removeappownerresponse
from sdk.types import BaseModel
from sdk.utils import FieldMetadata, PathParamMetadata, RequestMetadata
from typing import Optional, TypedDict
from typing_extensions import Annotated, NotRequired


class C1APIAppV1AppOwnersRemoveRequestTypedDict(TypedDict):
    app_id: str
    user_id: str
    remove_app_owner_request: NotRequired[shared_removeappownerrequest.RemoveAppOwnerRequestTypedDict]
    

class C1APIAppV1AppOwnersRemoveRequest(BaseModel):
    app_id: Annotated[str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))]
    user_id: Annotated[str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))]
    remove_app_owner_request: Annotated[Optional[shared_removeappownerrequest.RemoveAppOwnerRequest], FieldMetadata(request=RequestMetadata(media_type="application/json"))] = None
    

class C1APIAppV1AppOwnersRemoveResponseTypedDict(TypedDict):
    content_type: str
    r"""HTTP response content type for this operation"""
    status_code: int
    r"""HTTP response status code for this operation"""
    raw_response: httpx.Response
    r"""Raw HTTP response; suitable for custom response parsing"""
    remove_app_owner_response: NotRequired[shared_removeappownerresponse.RemoveAppOwnerResponseTypedDict]
    r"""Empty response with a status code indicating success."""
    

class C1APIAppV1AppOwnersRemoveResponse(BaseModel):
    content_type: str
    r"""HTTP response content type for this operation"""
    status_code: int
    r"""HTTP response status code for this operation"""
    raw_response: httpx.Response
    r"""Raw HTTP response; suitable for custom response parsing"""
    remove_app_owner_response: Optional[shared_removeappownerresponse.RemoveAppOwnerResponse] = None
    r"""Empty response with a status code indicating success."""
    
