"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
import httpx
from sdk.models.shared import (
    functionsservicecreatetagrequest as shared_functionsservicecreatetagrequest,
    functionsservicecreatetagresponse as shared_functionsservicecreatetagresponse,
)
from sdk.types import BaseModel
from sdk.utils import FieldMetadata, PathParamMetadata, RequestMetadata
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class C1APIFunctionsV1FunctionsServiceCreateTagRequestTypedDict(TypedDict):
    functions_service_create_tag_request: shared_functionsservicecreatetagrequest.FunctionsServiceCreateTagRequestTypedDict
    function_id: str


class C1APIFunctionsV1FunctionsServiceCreateTagRequest(BaseModel):
    functions_service_create_tag_request: Annotated[
        shared_functionsservicecreatetagrequest.FunctionsServiceCreateTagRequest,
        FieldMetadata(request=RequestMetadata(media_type="application/json")),
    ]

    function_id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]


class C1APIFunctionsV1FunctionsServiceCreateTagResponseTypedDict(TypedDict):
    content_type: str
    r"""HTTP response content type for this operation"""
    status_code: int
    r"""HTTP response status code for this operation"""
    raw_response: httpx.Response
    r"""Raw HTTP response; suitable for custom response parsing"""
    functions_service_create_tag_response: NotRequired[
        shared_functionsservicecreatetagresponse.FunctionsServiceCreateTagResponseTypedDict
    ]
    r"""Successful response"""


class C1APIFunctionsV1FunctionsServiceCreateTagResponse(BaseModel):
    content_type: str
    r"""HTTP response content type for this operation"""

    status_code: int
    r"""HTTP response status code for this operation"""

    raw_response: httpx.Response
    r"""Raw HTTP response; suitable for custom response parsing"""

    functions_service_create_tag_response: Optional[
        shared_functionsservicecreatetagresponse.FunctionsServiceCreateTagResponse
    ] = None
    r"""Successful response"""
