"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .donotsave import DoNotSave, DoNotSaveTypedDict
from .savetovault import SaveToVault, SaveToVaultTypedDict
from conductorone_sdk.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
)
import pydantic
from pydantic import model_serializer
from typing import Any, Dict, Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class AccountProvisionTypedDict(TypedDict):
    r"""The AccountProvision message.

    This message contains a oneof named storage_type. Only a single field of the following list may be set at a time:
    - saveToVault
    - doNotSave

    """

    do_not_save: NotRequired[Nullable[DoNotSaveTypedDict]]
    r"""The DoNotSave message."""
    save_to_vault: NotRequired[Nullable[SaveToVaultTypedDict]]
    r"""The SaveToVault message."""
    config: NotRequired[Dict[str, Any]]
    connector_id: NotRequired[str]
    r"""The connectorId field."""
    schema_id: NotRequired[str]
    r"""The schemaId field."""


class AccountProvision(BaseModel):
    r"""The AccountProvision message.

    This message contains a oneof named storage_type. Only a single field of the following list may be set at a time:
    - saveToVault
    - doNotSave

    """

    do_not_save: Annotated[
        OptionalNullable[DoNotSave], pydantic.Field(alias="doNotSave")
    ] = UNSET
    r"""The DoNotSave message."""

    save_to_vault: Annotated[
        OptionalNullable[SaveToVault], pydantic.Field(alias="saveToVault")
    ] = UNSET
    r"""The SaveToVault message."""

    config: Optional[Dict[str, Any]] = None

    connector_id: Annotated[Optional[str], pydantic.Field(alias="connectorId")] = None
    r"""The connectorId field."""

    schema_id: Annotated[Optional[str], pydantic.Field(alias="schemaId")] = None
    r"""The schemaId field."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = [
            "DoNotSave",
            "SaveToVault",
            "config",
            "connectorId",
            "schemaId",
        ]
        nullable_fields = ["DoNotSave", "SaveToVault"]
        null_default_fields = []

        serialized = handler(self)

        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)
            serialized.pop(k, None)

            optional_nullable = k in optional_fields and k in nullable_fields
            is_set = (
                self.__pydantic_fields_set__.intersection({n})
                or k in null_default_fields
            )  # pylint: disable=no-member

            if val is not None and val != UNSET_SENTINEL:
                m[k] = val
            elif val != UNSET_SENTINEL and (
                not k in optional_fields or (optional_nullable and is_set)
            ):
                m[k] = val

        return m
