"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from conductorone_sdk.types import BaseModel
from typing_extensions import TypedDict


class AppEntitlementAutomationLastRunStatusInputTypedDict(TypedDict):
    r"""The AppEntitlementAutomationLastRunStatus message."""


class AppEntitlementAutomationLastRunStatusInput(BaseModel):
    r"""The AppEntitlementAutomationLastRunStatus message."""
