"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .userref import UserRef, UserRefTypedDict
from conductorone_sdk.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
)
import pydantic
from pydantic import model_serializer
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class CloseActionTypedDict(TypedDict):
    r"""The CloseAction message.

    This message contains a oneof named user_identifier. Only a single field of the following list may be set at a time:
    - userIdCel
    - userRef

    """

    user_ref: NotRequired[UserRefTypedDict]
    r"""A reference to a user."""
    use_subject_user: NotRequired[bool]
    r"""If true, the step will use the subject user of the automation as the subject."""
    user_id_cel: NotRequired[Nullable[str]]
    r"""The userIdCel field.
    This field is part of the `user_identifier` oneof.
    See the documentation for `c1.api.automations.v1.CloseAction` for more details.
    """


class CloseAction(BaseModel):
    r"""The CloseAction message.

    This message contains a oneof named user_identifier. Only a single field of the following list may be set at a time:
    - userIdCel
    - userRef

    """

    user_ref: Annotated[Optional[UserRef], pydantic.Field(alias="userRef")] = None
    r"""A reference to a user."""

    use_subject_user: Annotated[
        Optional[bool], pydantic.Field(alias="useSubjectUser")
    ] = None
    r"""If true, the step will use the subject user of the automation as the subject."""

    user_id_cel: Annotated[OptionalNullable[str], pydantic.Field(alias="userIdCel")] = (
        UNSET
    )
    r"""The userIdCel field.
    This field is part of the `user_identifier` oneof.
    See the documentation for `c1.api.automations.v1.CloseAction` for more details.
    """

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = ["UserRef", "useSubjectUser", "userIdCel"]
        nullable_fields = ["userIdCel"]
        null_default_fields = []

        serialized = handler(self)

        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)
            serialized.pop(k, None)

            optional_nullable = k in optional_fields and k in nullable_fields
            is_set = (
                self.__pydantic_fields_set__.intersection({n})
                or k in null_default_fields
            )  # pylint: disable=no-member

            if val is not None and val != UNSET_SENTINEL:
                m[k] = val
            elif val != UNSET_SENTINEL and (
                not k in optional_fields or (optional_nullable and is_set)
            ):
                m[k] = val

        return m
