"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from conductorone_sdk import utils
from conductorone_sdk.models import shared
from conductorone_sdk.types import BaseModel
from conductorone_sdk.utils import validate_open_enum
from enum import Enum
import pydantic
from pydantic import field_serializer
from pydantic.functional_validators import PlainValidator
from typing_extensions import Annotated, TypedDict


class ResourceType(str, Enum, metaclass=utils.OpenEnumMeta):
    r"""The resourceType field."""

    ROLE = "ROLE"
    GROUP = "GROUP"
    LICENSE = "LICENSE"
    PROJECT = "PROJECT"
    CATALOG = "CATALOG"
    CUSTOM = "CUSTOM"
    VAULT = "VAULT"
    PROFILE_TYPE = "PROFILE_TYPE"


class CreateManuallyManagedResourceTypeRequestTypedDict(TypedDict):
    r"""The CreateManuallyManagedResourceTypeRequest message."""

    display_name: str
    r"""The displayName field."""
    resource_type: ResourceType
    r"""The resourceType field."""


class CreateManuallyManagedResourceTypeRequest(BaseModel):
    r"""The CreateManuallyManagedResourceTypeRequest message."""

    display_name: Annotated[str, pydantic.Field(alias="displayName")]
    r"""The displayName field."""

    resource_type: Annotated[
        Annotated[ResourceType, PlainValidator(validate_open_enum(False))],
        pydantic.Field(alias="resourceType"),
    ]
    r"""The resourceType field."""

    @field_serializer("resource_type")
    def serialize_resource_type(self, value):
        if isinstance(value, str):
            try:
                return shared.ResourceType(value)
            except ValueError:
                return value
        return value
