"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .appresource import AppResource, AppResourceTypedDict
from conductorone_sdk.types import BaseModel
import pydantic
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class CreateManuallyManagedAppResourceResponseTypedDict(TypedDict):
    r"""The CreateManuallyManagedAppResourceResponse message."""

    app_resource: NotRequired[AppResourceTypedDict]
    r"""The app resource message is a single resource that can have entitlements.

    This message contains a oneof named metadata. Only a single field of the following list may be set at a time:
    - secretTrait

    """


class CreateManuallyManagedAppResourceResponse(BaseModel):
    r"""The CreateManuallyManagedAppResourceResponse message."""

    app_resource: Annotated[
        Optional[AppResource], pydantic.Field(alias="appResource")
    ] = None
    r"""The app resource message is a single resource that can have entitlements.

    This message contains a oneof named metadata. Only a single field of the following list may be set at a time:
    - secretTrait

    """
