"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from conductorone_sdk.types import BaseModel
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class CreateComplianceFrameworkAttributeValueRequestTypedDict(TypedDict):
    r"""The CreateComplianceFrameworkAttributeValueRequest message."""

    value: NotRequired[str]
    r"""The value field."""


class CreateComplianceFrameworkAttributeValueRequest(BaseModel):
    r"""The CreateComplianceFrameworkAttributeValueRequest message."""

    value: Optional[str] = None
    r"""The value field."""
