"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .appentitlementproxyview import (
    AppEntitlementProxyView,
    AppEntitlementProxyViewTypedDict,
)
from conductorone_sdk.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
)
import pydantic
from pydantic import ConfigDict, model_serializer
from typing import Any, Dict, List, Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class CreateAppEntitlementProxyResponseExpandedTypedDict(TypedDict):
    r"""Contains an arbitrary serialized message along with a @type that describes the type of the serialized message."""

    at_type: NotRequired[str]
    r"""The type of the serialized message."""


class CreateAppEntitlementProxyResponseExpanded(BaseModel):
    r"""Contains an arbitrary serialized message along with a @type that describes the type of the serialized message."""

    model_config = ConfigDict(
        populate_by_name=True, arbitrary_types_allowed=True, extra="allow"
    )
    __pydantic_extra__: Dict[str, Any] = pydantic.Field(init=False)

    at_type: Annotated[Optional[str], pydantic.Field(alias="@type")] = None
    r"""The type of the serialized message."""

    @property
    def additional_properties(self):
        return self.__pydantic_extra__

    @additional_properties.setter
    def additional_properties(self, value):
        self.__pydantic_extra__ = value  # pyright: ignore[reportIncompatibleVariableOverride]


class CreateAppEntitlementProxyResponseTypedDict(TypedDict):
    r"""The CreateAppEntitlementProxyResponse message."""

    app_entitlement_proxy_view: NotRequired[AppEntitlementProxyViewTypedDict]
    r"""The AppEntitlementProxyView message."""
    expanded: NotRequired[
        Nullable[List[CreateAppEntitlementProxyResponseExpandedTypedDict]]
    ]
    r"""The expanded field."""


class CreateAppEntitlementProxyResponse(BaseModel):
    r"""The CreateAppEntitlementProxyResponse message."""

    app_entitlement_proxy_view: Annotated[
        Optional[AppEntitlementProxyView],
        pydantic.Field(alias="appProxyEntitlementView"),
    ] = None
    r"""The AppEntitlementProxyView message."""

    expanded: OptionalNullable[List[CreateAppEntitlementProxyResponseExpanded]] = UNSET
    r"""The expanded field."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = ["AppEntitlementProxyView", "expanded"]
        nullable_fields = ["expanded"]
        null_default_fields = []

        serialized = handler(self)

        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)
            serialized.pop(k, None)

            optional_nullable = k in optional_fields and k in nullable_fields
            is_set = (
                self.__pydantic_fields_set__.intersection({n})
                or k in null_default_fields
            )  # pylint: disable=no-member

            if val is not None and val != UNSET_SENTINEL:
                m[k] = val
            elif val != UNSET_SENTINEL and (
                not k in optional_fields or (optional_nullable and is_set)
            ):
                m[k] = val

        return m
