"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from conductorone_sdk.types import BaseModel
from typing_extensions import TypedDict


class DeleteAppResourceOwnersRequestTypedDict(TypedDict):
    r"""The request message for deleting app resource owners."""


class DeleteAppResourceOwnersRequest(BaseModel):
    r"""The request message for deleting app resource owners."""
