"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from conductorone_sdk.types import BaseModel
from typing_extensions import TypedDict


class DeleteManuallyManagedAppResourceRequestTypedDict(TypedDict):
    r"""The DeleteManuallyManagedAppResourceRequest message."""


class DeleteManuallyManagedAppResourceRequest(BaseModel):
    r"""The DeleteManuallyManagedAppResourceRequest message."""
