"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from conductorone_sdk.types import BaseModel
from typing_extensions import TypedDict


class DeleteAppResponseTypedDict(TypedDict):
    r"""Empty response body. Status code indicates success."""


class DeleteAppResponse(BaseModel):
    r"""Empty response body. Status code indicates success."""
