"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from conductorone_sdk.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
)
import pydantic
from pydantic import model_serializer
from typing import List, Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class DurationRulesTypedDict(TypedDict):
    r"""DurationRules describe the constraints applied exclusively to the
    `google.protobuf.Duration` well-known type
    """

    const: NotRequired[str]
    gt: NotRequired[str]
    gte: NotRequired[str]
    in_: NotRequired[Nullable[List[str]]]
    r"""In specifies that this field must be equal to one of the specified
    values
    """
    lt: NotRequired[str]
    lte: NotRequired[str]
    not_in: NotRequired[Nullable[List[str]]]
    r"""NotIn specifies that this field cannot be equal to one of the specified
    values
    """
    required: NotRequired[bool]
    r"""Required specifies that this field must be set"""


class DurationRules(BaseModel):
    r"""DurationRules describe the constraints applied exclusively to the
    `google.protobuf.Duration` well-known type
    """

    const: Optional[str] = None

    gt: Optional[str] = None

    gte: Optional[str] = None

    in_: Annotated[OptionalNullable[List[str]], pydantic.Field(alias="in")] = UNSET
    r"""In specifies that this field must be equal to one of the specified
    values
    """

    lt: Optional[str] = None

    lte: Optional[str] = None

    not_in: Annotated[OptionalNullable[List[str]], pydantic.Field(alias="notIn")] = (
        UNSET
    )
    r"""NotIn specifies that this field cannot be equal to one of the specified
    values
    """

    required: Optional[bool] = None
    r"""Required specifies that this field must be set"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = ["const", "gt", "gte", "in", "lt", "lte", "notIn", "required"]
        nullable_fields = ["in", "notIn"]
        null_default_fields = []

        serialized = handler(self)

        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)
            serialized.pop(k, None)

            optional_nullable = k in optional_fields and k in nullable_fields
            is_set = (
                self.__pydantic_fields_set__.intersection({n})
                or k in null_default_fields
            )  # pylint: disable=no-member

            if val is not None and val != UNSET_SENTINEL:
                m[k] = val
            elif val != UNSET_SENTINEL and (
                not k in optional_fields or (optional_nullable and is_set)
            ):
                m[k] = val

        return m
