"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from conductorone_sdk.types import BaseModel
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class EditorValidateRequestTypedDict(TypedDict):
    r"""The EditorValidateRequest message."""

    text: NotRequired[str]
    r"""The text field."""


class EditorValidateRequest(BaseModel):
    r"""The EditorValidateRequest message."""

    text: Optional[str] = None
    r"""The text field."""
