"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .appentitlementref import AppEntitlementRef, AppEntitlementRefTypedDict
from conductorone_sdk.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
)
import pydantic
from pydantic import model_serializer
from typing import List
from typing_extensions import Annotated, NotRequired, TypedDict


class EntitlementInclusionListTypedDict(TypedDict):
    r"""The EntitlementInclusionList message."""

    app_entitlement_refs: NotRequired[Nullable[List[AppEntitlementRefTypedDict]]]
    r"""The appEntitlementRefs field."""


class EntitlementInclusionList(BaseModel):
    r"""The EntitlementInclusionList message."""

    app_entitlement_refs: Annotated[
        OptionalNullable[List[AppEntitlementRef]],
        pydantic.Field(alias="appEntitlementRefs"),
    ] = UNSET
    r"""The appEntitlementRefs field."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = ["appEntitlementRefs"]
        nullable_fields = ["appEntitlementRefs"]
        null_default_fields = []

        serialized = handler(self)

        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)
            serialized.pop(k, None)

            optional_nullable = k in optional_fields and k in nullable_fields
            is_set = (
                self.__pydantic_fields_set__.intersection({n})
                or k in null_default_fields
            )  # pylint: disable=no-member

            if val is not None and val != UNSET_SENTINEL:
                m[k] = val
            elif val != UNSET_SENTINEL and (
                not k in optional_fields or (optional_nullable and is_set)
            ):
                m[k] = val

        return m
