"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .fileinputfield import FileInputField, FileInputFieldTypedDict
from conductorone_sdk.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
)
from conductorone_sdk.utils import serialize_int, validate_int
import pydantic
from pydantic import model_serializer
from pydantic.functional_serializers import PlainSerializer
from pydantic.functional_validators import BeforeValidator
from typing import List
from typing_extensions import Annotated, NotRequired, TypedDict


class FileFieldTypedDict(TypedDict):
    r"""The FileField message.

    This message contains a oneof named view. Only a single field of the following list may be set at a time:
    - fileInputField


    This message contains a oneof named _max_file_size. Only a single field of the following list may be set at a time:
    - maxFileSize

    """

    file_input_field: NotRequired[Nullable[FileInputFieldTypedDict]]
    r"""The FileInputField message."""
    accepted_file_types: NotRequired[Nullable[List[str]]]
    r"""The acceptedFileTypes field."""
    max_file_size: NotRequired[Nullable[int]]
    r"""The maxFileSize field.
    This field is part of the `_max_file_size` oneof.
    See the documentation for `c1.api.form.v1.FileField` for more details.
    """


class FileField(BaseModel):
    r"""The FileField message.

    This message contains a oneof named view. Only a single field of the following list may be set at a time:
    - fileInputField


    This message contains a oneof named _max_file_size. Only a single field of the following list may be set at a time:
    - maxFileSize

    """

    file_input_field: Annotated[
        OptionalNullable[FileInputField], pydantic.Field(alias="fileInputField")
    ] = UNSET
    r"""The FileInputField message."""

    accepted_file_types: Annotated[
        OptionalNullable[List[str]], pydantic.Field(alias="acceptedFileTypes")
    ] = UNSET
    r"""The acceptedFileTypes field."""

    max_file_size: Annotated[
        Annotated[
            OptionalNullable[int],
            BeforeValidator(validate_int),
            PlainSerializer(serialize_int(True)),
        ],
        pydantic.Field(alias="maxFileSize"),
    ] = UNSET
    r"""The maxFileSize field.
    This field is part of the `_max_file_size` oneof.
    See the documentation for `c1.api.form.v1.FileField` for more details.
    """

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = ["FileInputField", "acceptedFileTypes", "maxFileSize"]
        nullable_fields = ["FileInputField", "acceptedFileTypes", "maxFileSize"]
        null_default_fields = []

        serialized = handler(self)

        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)
            serialized.pop(k, None)

            optional_nullable = k in optional_fields and k in nullable_fields
            is_set = (
                self.__pydantic_fields_set__.intersection({n})
                or k in null_default_fields
            )  # pylint: disable=no-member

            if val is not None and val != UNSET_SENTINEL:
                m[k] = val
            elif val != UNSET_SENTINEL and (
                not k in optional_fields or (optional_nullable and is_set)
            ):
                m[k] = val

        return m
