"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .form_input import FormInput, FormInputTypedDict
from conductorone_sdk.types import BaseModel
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class FormTypedDict(TypedDict):
    r"""The Form message."""

    form: NotRequired[FormInputTypedDict]
    r"""A form is a collection of fields to be filled out by a user"""


class Form(BaseModel):
    r"""The Form message."""

    form: Optional[FormInput] = None
    r"""A form is a collection of fields to be filled out by a user"""
