"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .attributevalue import AttributeValue, AttributeValueTypedDict
from conductorone_sdk.types import BaseModel
import pydantic
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class GetComplianceFrameworkAttributeValueResponseTypedDict(TypedDict):
    r"""The GetComplianceFrameworkAttributeValueResponse message."""

    attribute_value: NotRequired[AttributeValueTypedDict]
    r"""AttributeValue is the value of an attribute of a defined type."""


class GetComplianceFrameworkAttributeValueResponse(BaseModel):
    r"""The GetComplianceFrameworkAttributeValueResponse message."""

    attribute_value: Annotated[
        Optional[AttributeValue], pydantic.Field(alias="value")
    ] = None
    r"""AttributeValue is the value of an attribute of a defined type."""
