"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .stepuptransaction import StepUpTransaction, StepUpTransactionTypedDict
from conductorone_sdk.types import BaseModel
import pydantic
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class GetStepUpTransactionResponseTypedDict(TypedDict):
    r"""Response message containing the requested step-up transaction"""

    step_up_transaction: NotRequired[StepUpTransactionTypedDict]
    r"""StepUpTransaction represents a record of a step-up authentication attempt

    This message contains a oneof named target. Only a single field of the following list may be set at a time:
    - approveTask
    - test

    """


class GetStepUpTransactionResponse(BaseModel):
    r"""Response message containing the requested step-up transaction"""

    step_up_transaction: Annotated[
        Optional[StepUpTransaction], pydantic.Field(alias="transaction")
    ] = None
    r"""StepUpTransaction represents a record of a step-up authentication attempt

    This message contains a oneof named target. Only a single field of the following list may be set at a time:
    - approveTask
    - test

    """
