"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from conductorone_sdk.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
)
from datetime import datetime
import pydantic
from pydantic import model_serializer
from typing import List, Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class PersonalClientInputTypedDict(TypedDict):
    r"""The PersonalClient message contains information about a presonal client credential."""

    allow_source_cidr: NotRequired[Nullable[List[str]]]
    r"""If set, only allows the CIDRs in the array to use the credential."""
    display_name: NotRequired[str]
    r"""The display name of the personal client credential."""
    expires_time: NotRequired[datetime]
    scoped_roles: NotRequired[Nullable[List[str]]]
    r"""scoped_roles provides a list of IAM Roles
    that this OAuth2 Client's API permissions
    are reduced to. The permissions granted to OAuth2 Client
    are AND'ed against the owning User's own permissions.
    """


class PersonalClientInput(BaseModel):
    r"""The PersonalClient message contains information about a presonal client credential."""

    allow_source_cidr: Annotated[
        OptionalNullable[List[str]], pydantic.Field(alias="allowSourceCidr")
    ] = UNSET
    r"""If set, only allows the CIDRs in the array to use the credential."""

    display_name: Annotated[Optional[str], pydantic.Field(alias="displayName")] = None
    r"""The display name of the personal client credential."""

    expires_time: Annotated[Optional[datetime], pydantic.Field(alias="expiresTime")] = (
        None
    )

    scoped_roles: Annotated[
        OptionalNullable[List[str]], pydantic.Field(alias="scopedRoles")
    ] = UNSET
    r"""scoped_roles provides a list of IAM Roles
    that this OAuth2 Client's API permissions
    are reduced to. The permissions granted to OAuth2 Client
    are AND'ed against the owning User's own permissions.
    """

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = [
            "allowSourceCidr",
            "displayName",
            "expiresTime",
            "scopedRoles",
        ]
        nullable_fields = ["allowSourceCidr", "scopedRoles"]
        null_default_fields = []

        serialized = handler(self)

        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)
            serialized.pop(k, None)

            optional_nullable = k in optional_fields and k in nullable_fields
            is_set = (
                self.__pydantic_fields_set__.intersection({n})
                or k in null_default_fields
            )  # pylint: disable=no-member

            if val is not None and val != UNSET_SENTINEL:
                m[k] = val
            elif val != UNSET_SENTINEL and (
                not k in optional_fields or (optional_nullable and is_set)
            ):
                m[k] = val

        return m
