"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from conductorone_sdk.types import BaseModel
from typing_extensions import TypedDict


class RequestCatalogManagementServiceAddAppEntitlementsResponseTypedDict(TypedDict):
    r"""Empty response with a status code indicating success."""


class RequestCatalogManagementServiceAddAppEntitlementsResponse(BaseModel):
    r"""Empty response with a status code indicating success."""
