"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from conductorone_sdk.types import BaseModel
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class ResponsePolicyApprovalStepApproveTypedDict(TypedDict):
    r"""The ResponsePolicyApprovalStepApprove message."""

    comment: NotRequired[str]
    r"""optional comment"""


class ResponsePolicyApprovalStepApprove(BaseModel):
    r"""The ResponsePolicyApprovalStepApprove message."""

    comment: Optional[str] = None
    r"""optional comment"""
