"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from conductorone_sdk.types import BaseModel
import pydantic
from typing_extensions import Annotated, TypedDict


class RunDelayedTypedDict(TypedDict):
    r"""The RunDelayed message."""

    cold_start_delay_days: int
    r"""The coldStartDelayDays field."""


class RunDelayed(BaseModel):
    r"""The RunDelayed message."""

    cold_start_delay_days: Annotated[int, pydantic.Field(alias="coldStartDelayDays")]
    r"""The coldStartDelayDays field."""
