"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .taskaction1 import TaskAction1, TaskAction1TypedDict
from conductorone_sdk.types import BaseModel
import pydantic
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class TaskAuditActionSubmittedTypedDict(TypedDict):
    r"""The TaskAuditActionSubmitted message."""

    task_action: NotRequired[TaskAction1TypedDict]
    r"""The TaskAction message."""


class TaskAuditActionSubmitted(BaseModel):
    r"""The TaskAuditActionSubmitted message."""

    task_action: Annotated[Optional[TaskAction1], pydantic.Field(alias="action")] = None
    r"""The TaskAction message."""
