"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from conductorone_sdk.types import BaseModel
import pydantic
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class TaskAuditWaitForAnalysisStepWaitingTypedDict(TypedDict):
    r"""The TaskAuditWaitForAnalysisStepWaiting message."""

    step_id: NotRequired[str]
    r"""The stepId field."""


class TaskAuditWaitForAnalysisStepWaiting(BaseModel):
    r"""The TaskAuditWaitForAnalysisStepWaiting message."""

    step_id: Annotated[Optional[str], pydantic.Field(alias="stepId")] = None
    r"""The stepId field."""
