"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from conductorone_sdk.types import BaseModel
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class TaskAuditGrantDurationUpdatedTypedDict(TypedDict):
    r"""The TaskAuditGrantDurationUpdated message."""

    duration: NotRequired[str]


class TaskAuditGrantDurationUpdated(BaseModel):
    r"""The TaskAuditGrantDurationUpdated message."""

    duration: Optional[str] = None
