"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from conductorone_sdk import utils
from conductorone_sdk.models import shared
from conductorone_sdk.types import BaseModel
from conductorone_sdk.utils import validate_open_enum
from enum import Enum
import pydantic
from pydantic import field_serializer
from pydantic.functional_validators import PlainValidator
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class PreviousState(str, Enum, metaclass=utils.OpenEnumMeta):
    r"""The previousState field."""

    TASK_STATE_UNSPECIFIED = "TASK_STATE_UNSPECIFIED"
    TASK_STATE_OPEN = "TASK_STATE_OPEN"
    TASK_STATE_CLOSED = "TASK_STATE_CLOSED"


class TaskAuditStateChangeTypedDict(TypedDict):
    r"""The TaskAuditStateChange message."""

    previous_state: NotRequired[PreviousState]
    r"""The previousState field."""


class TaskAuditStateChange(BaseModel):
    r"""The TaskAuditStateChange message."""

    previous_state: Annotated[
        Annotated[Optional[PreviousState], PlainValidator(validate_open_enum(False))],
        pydantic.Field(alias="previousState"),
    ] = None
    r"""The previousState field."""

    @field_serializer("previous_state")
    def serialize_previous_state(self, value):
        if isinstance(value, str):
            try:
                return shared.PreviousState(value)
            except ValueError:
                return value
        return value
