"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from conductorone_sdk.types import BaseModel
from typing_extensions import TypedDict


class UnconfiguredProvisionTypedDict(TypedDict):
    r"""The UnconfiguredProvision message."""


class UnconfiguredProvision(BaseModel):
    r"""The UnconfiguredProvision message."""
