"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from conductorone_sdk.types import BaseModel
import pydantic
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class UpdateStepUpProviderSecretRequestTypedDict(TypedDict):
    r"""The UpdateStepUpProviderSecretRequest message."""

    client_secret: NotRequired[str]
    r"""The clientSecret field."""


class UpdateStepUpProviderSecretRequest(BaseModel):
    r"""The UpdateStepUpProviderSecretRequest message."""

    client_secret: Annotated[Optional[str], pydantic.Field(alias="clientSecret")] = None
    r"""The clientSecret field."""
