"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from conductorone_sdk.types import BaseModel
import pydantic
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class UserPropertiesTypedDict(TypedDict):
    r"""The UserProperties message."""

    display_name_cel: NotRequired[str]
    r"""The displayNameCel field."""
    email_cel: NotRequired[str]
    r"""The emailCel field."""
    profile_attribute_cel: NotRequired[str]
    r"""The profileAttributeCel field."""
    username_cel: NotRequired[str]
    r"""The usernameCel field."""


class UserProperties(BaseModel):
    r"""The UserProperties message."""

    display_name_cel: Annotated[
        Optional[str], pydantic.Field(alias="displayNameCel")
    ] = None
    r"""The displayNameCel field."""

    email_cel: Annotated[Optional[str], pydantic.Field(alias="emailCel")] = None
    r"""The emailCel field."""

    profile_attribute_cel: Annotated[
        Optional[str], pydantic.Field(alias="profileAttributeCel")
    ] = None
    r"""The profileAttributeCel field."""

    username_cel: Annotated[Optional[str], pydantic.Field(alias="usernameCel")] = None
    r"""The usernameCel field."""
