"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from conductorone_sdk.types import BaseModel
import pydantic
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class WebhookSourcePolicyPostActionTypedDict(TypedDict):
    r"""The WebhookSourcePolicyPostAction message."""

    ticket_id: NotRequired[str]
    r"""The ticketId field."""


class WebhookSourcePolicyPostAction(BaseModel):
    r"""The WebhookSourcePolicyPostAction message."""

    ticket_id: Annotated[Optional[str], pydantic.Field(alias="ticketId")] = None
    r"""The ticketId field."""
