"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .webhooklistenerauthhmac import (
    WebhookListenerAuthHMAC,
    WebhookListenerAuthHMACTypedDict,
)
from .webhooklistenerauthjwt import (
    WebhookListenerAuthJWT,
    WebhookListenerAuthJWTTypedDict,
)
from conductorone_sdk.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
)
import pydantic
from pydantic import model_serializer
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class WebhookAutomationTriggerTypedDict(TypedDict):
    r"""The WebhookAutomationTrigger message.

    This message contains a oneof named auth_config. Only a single field of the following list may be set at a time:
    - jwt
    - hmac

    """

    webhook_listener_auth_hmac: NotRequired[Nullable[WebhookListenerAuthHMACTypedDict]]
    r"""The WebhookListenerAuthHMAC message."""
    webhook_listener_auth_jwt: NotRequired[Nullable[WebhookListenerAuthJWTTypedDict]]
    r"""The WebhookListenerAuthJWT message."""
    listener_id: NotRequired[str]
    r"""Optional existing listener ID (hidden field from frontend)"""


class WebhookAutomationTrigger(BaseModel):
    r"""The WebhookAutomationTrigger message.

    This message contains a oneof named auth_config. Only a single field of the following list may be set at a time:
    - jwt
    - hmac

    """

    webhook_listener_auth_hmac: Annotated[
        OptionalNullable[WebhookListenerAuthHMAC], pydantic.Field(alias="hmac")
    ] = UNSET
    r"""The WebhookListenerAuthHMAC message."""

    webhook_listener_auth_jwt: Annotated[
        OptionalNullable[WebhookListenerAuthJWT], pydantic.Field(alias="jwt")
    ] = UNSET
    r"""The WebhookListenerAuthJWT message."""

    listener_id: Annotated[Optional[str], pydantic.Field(alias="listenerId")] = None
    r"""Optional existing listener ID (hidden field from frontend)"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = [
            "WebhookListenerAuthHMAC",
            "WebhookListenerAuthJWT",
            "listenerId",
        ]
        nullable_fields = ["WebhookListenerAuthHMAC", "WebhookListenerAuthJWT"]
        null_default_fields = []

        serialized = handler(self)

        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)
            serialized.pop(k, None)

            optional_nullable = k in optional_fields and k in nullable_fields
            is_set = (
                self.__pydantic_fields_set__.intersection({n})
                or k in null_default_fields
            )  # pylint: disable=no-member

            if val is not None and val != UNSET_SENTINEL:
                m[k] = val
            elif val != UNSET_SENTINEL and (
                not k in optional_fields or (optional_nullable and is_set)
            ):
                m[k] = val

        return m
