"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from .basesdk import BaseSDK
from .httpclient import AsyncHttpClient, ClientOwner, HttpClient, close_clients
from .sdkconfiguration import SDKConfiguration
from .utils.logger import Logger, get_default_logger
from .utils.retries import RetryConfig
import httpx
import importlib
from sdk import utils
from sdk._hooks import SDKHooks
from sdk.models import shared
from sdk.types import OptionalNullable, UNSET
import sys
from typing import Callable, Dict, List, Optional, TYPE_CHECKING, Union, cast
import weakref

if TYPE_CHECKING:
    from sdk.accessconflict import AccessConflict
    from sdk.accountprovisionpolicytest import AccountProvisionPolicyTest
    from sdk.appaccessrequestsdefaults import AppAccessRequestsDefaults
    from sdk.appentitlementmonitorbinding import AppEntitlementMonitorBinding
    from sdk.appentitlementowners import AppEntitlementOwners
    from sdk.appentitlements import AppEntitlements
    from sdk.appentitlementsearch import AppEntitlementSearch
    from sdk.appentitlementsproxy import AppEntitlementsProxy
    from sdk.appentitlementuserbinding import AppEntitlementUserBinding
    from sdk.appowners import AppOwners
    from sdk.appreport import AppReport
    from sdk.appreportaction import AppReportAction
    from sdk.appresource import AppResource
    from sdk.appresourceowners import AppResourceOwners
    from sdk.appresourcesearch import AppResourceSearch
    from sdk.appresourcetype import AppResourceType
    from sdk.apps import Apps
    from sdk.appsearch import AppSearch
    from sdk.appusagecontrols import AppUsageControls
    from sdk.appuser import AppUser
    from sdk.attributes import Attributes
    from sdk.attributesearch import AttributeSearch
    from sdk.auth import Auth
    from sdk.automation import Automation
    from sdk.automationexecution import AutomationExecution
    from sdk.automationexecutionactions import AutomationExecutionActions
    from sdk.automationexecutionsearch import AutomationExecutionSearch
    from sdk.automationsearch import AutomationSearch
    from sdk.awsexternalidsettings import AWSExternalIDSettings
    from sdk.connector import Connector
    from sdk.connectorcatalog import ConnectorCatalog
    from sdk.directory import Directory
    from sdk.export import Export
    from sdk.exportssearch import ExportsSearch
    from sdk.functions import Functions
    from sdk.functionssearch import FunctionsSearch
    from sdk.orgdomain import OrgDomain
    from sdk.personalclient import PersonalClient
    from sdk.personalclientsearch import PersonalClientSearch
    from sdk.policies import Policies
    from sdk.policysearch import PolicySearch
    from sdk.policyvalidate import PolicyValidate
    from sdk.requestcatalogmanagement import RequestCatalogManagement
    from sdk.requestcatalogsearch import RequestCatalogSearch
    from sdk.roles import Roles
    from sdk.sessionsettings import SessionSettings
    from sdk.stepupprovider import StepUpProvider
    from sdk.stepuptransaction import StepUpTransaction
    from sdk.systemlog import SystemLog
    from sdk.task import Task
    from sdk.taskactions import TaskActions
    from sdk.taskaudit import TaskAudit
    from sdk.tasksearch import TaskSearch
    from sdk.user import User
    from sdk.usersearch import UserSearch
    from sdk.webhooks import Webhooks
    from sdk.webhookssearch import WebhooksSearch


class SDK(BaseSDK):
    r"""ConductorOne API: The ConductorOne API is a HTTP API for managing ConductorOne resources."""

    access_conflict: "AccessConflict"
    app_entitlement_monitor_binding: "AppEntitlementMonitorBinding"
    apps: "Apps"
    connector: "Connector"
    app_access_requests_defaults: "AppAccessRequestsDefaults"
    app_user: "AppUser"
    app_entitlements: "AppEntitlements"
    app_entitlement_search: "AppEntitlementSearch"
    app_entitlement_user_binding: "AppEntitlementUserBinding"
    app_entitlement_owners: "AppEntitlementOwners"
    app_owners: "AppOwners"
    app_report: "AppReport"
    app_report_action: "AppReportAction"
    app_resource_type: "AppResourceType"
    app_resource: "AppResource"
    app_resource_owners: "AppResourceOwners"
    app_usage_controls: "AppUsageControls"
    app_entitlements_proxy: "AppEntitlementsProxy"
    attributes: "Attributes"
    auth: "Auth"
    automation_execution: "AutomationExecution"
    automation_execution_search: "AutomationExecutionSearch"
    automation_execution_actions: "AutomationExecutionActions"
    automation_search: "AutomationSearch"
    automation: "Automation"
    request_catalog_management: "RequestCatalogManagement"
    connector_catalog: "ConnectorCatalog"
    directory: "Directory"
    functions: "Functions"
    personal_client: "PersonalClient"
    roles: "Roles"
    policies: "Policies"
    account_provision_policy_test: "AccountProvisionPolicyTest"
    policy_validate: "PolicyValidate"
    app_resource_search: "AppResourceSearch"
    app_search: "AppSearch"
    attribute_search: "AttributeSearch"
    functions_search: "FunctionsSearch"
    personal_client_search: "PersonalClientSearch"
    policy_search: "PolicySearch"
    request_catalog_search: "RequestCatalogSearch"
    step_up_provider: "StepUpProvider"
    step_up_transaction: "StepUpTransaction"
    exports_search: "ExportsSearch"
    task_search: "TaskSearch"
    user_search: "UserSearch"
    webhooks_search: "WebhooksSearch"
    aws_external_id_settings: "AWSExternalIDSettings"
    org_domain: "OrgDomain"
    session_settings: "SessionSettings"
    system_log: "SystemLog"
    export: "Export"
    task_audit: "TaskAudit"
    task: "Task"
    task_actions: "TaskActions"
    user: "User"
    webhooks: "Webhooks"
    _sub_sdk_map = {
        "access_conflict": ("sdk.accessconflict", "AccessConflict"),
        "app_entitlement_monitor_binding": (
            "sdk.appentitlementmonitorbinding",
            "AppEntitlementMonitorBinding",
        ),
        "apps": ("sdk.apps", "Apps"),
        "connector": ("sdk.connector", "Connector"),
        "app_access_requests_defaults": (
            "sdk.appaccessrequestsdefaults",
            "AppAccessRequestsDefaults",
        ),
        "app_user": ("sdk.appuser", "AppUser"),
        "app_entitlements": ("sdk.appentitlements", "AppEntitlements"),
        "app_entitlement_search": ("sdk.appentitlementsearch", "AppEntitlementSearch"),
        "app_entitlement_user_binding": (
            "sdk.appentitlementuserbinding",
            "AppEntitlementUserBinding",
        ),
        "app_entitlement_owners": ("sdk.appentitlementowners", "AppEntitlementOwners"),
        "app_owners": ("sdk.appowners", "AppOwners"),
        "app_report": ("sdk.appreport", "AppReport"),
        "app_report_action": ("sdk.appreportaction", "AppReportAction"),
        "app_resource_type": ("sdk.appresourcetype", "AppResourceType"),
        "app_resource": ("sdk.appresource", "AppResource"),
        "app_resource_owners": ("sdk.appresourceowners", "AppResourceOwners"),
        "app_usage_controls": ("sdk.appusagecontrols", "AppUsageControls"),
        "app_entitlements_proxy": ("sdk.appentitlementsproxy", "AppEntitlementsProxy"),
        "attributes": ("sdk.attributes", "Attributes"),
        "auth": ("sdk.auth", "Auth"),
        "automation_execution": ("sdk.automationexecution", "AutomationExecution"),
        "automation_execution_search": (
            "sdk.automationexecutionsearch",
            "AutomationExecutionSearch",
        ),
        "automation_execution_actions": (
            "sdk.automationexecutionactions",
            "AutomationExecutionActions",
        ),
        "automation_search": ("sdk.automationsearch", "AutomationSearch"),
        "automation": ("sdk.automation", "Automation"),
        "request_catalog_management": (
            "sdk.requestcatalogmanagement",
            "RequestCatalogManagement",
        ),
        "connector_catalog": ("sdk.connectorcatalog", "ConnectorCatalog"),
        "directory": ("sdk.directory", "Directory"),
        "functions": ("sdk.functions", "Functions"),
        "personal_client": ("sdk.personalclient", "PersonalClient"),
        "roles": ("sdk.roles", "Roles"),
        "policies": ("sdk.policies", "Policies"),
        "account_provision_policy_test": (
            "sdk.accountprovisionpolicytest",
            "AccountProvisionPolicyTest",
        ),
        "policy_validate": ("sdk.policyvalidate", "PolicyValidate"),
        "app_resource_search": ("sdk.appresourcesearch", "AppResourceSearch"),
        "app_search": ("sdk.appsearch", "AppSearch"),
        "attribute_search": ("sdk.attributesearch", "AttributeSearch"),
        "functions_search": ("sdk.functionssearch", "FunctionsSearch"),
        "personal_client_search": ("sdk.personalclientsearch", "PersonalClientSearch"),
        "policy_search": ("sdk.policysearch", "PolicySearch"),
        "request_catalog_search": ("sdk.requestcatalogsearch", "RequestCatalogSearch"),
        "step_up_provider": ("sdk.stepupprovider", "StepUpProvider"),
        "step_up_transaction": ("sdk.stepuptransaction", "StepUpTransaction"),
        "exports_search": ("sdk.exportssearch", "ExportsSearch"),
        "task_search": ("sdk.tasksearch", "TaskSearch"),
        "user_search": ("sdk.usersearch", "UserSearch"),
        "webhooks_search": ("sdk.webhookssearch", "WebhooksSearch"),
        "aws_external_id_settings": (
            "sdk.awsexternalidsettings",
            "AWSExternalIDSettings",
        ),
        "org_domain": ("sdk.orgdomain", "OrgDomain"),
        "session_settings": ("sdk.sessionsettings", "SessionSettings"),
        "system_log": ("sdk.systemlog", "SystemLog"),
        "export": ("sdk.export", "Export"),
        "task_audit": ("sdk.taskaudit", "TaskAudit"),
        "task": ("sdk.task", "Task"),
        "task_actions": ("sdk.taskactions", "TaskActions"),
        "user": ("sdk.user", "User"),
        "webhooks": ("sdk.webhooks", "Webhooks"),
    }

    def __init__(
        self,
        security: Union[shared.Security, Callable[[], shared.Security]],
        tenant_domain: Optional[str] = None,
        server_idx: Optional[int] = None,
        server_url: Optional[str] = None,
        url_params: Optional[Dict[str, str]] = None,
        client: Optional[HttpClient] = None,
        async_client: Optional[AsyncHttpClient] = None,
        retry_config: OptionalNullable[RetryConfig] = UNSET,
        timeout_ms: Optional[int] = None,
        debug_logger: Optional[Logger] = None,
    ) -> None:
        r"""Instantiates the SDK configuring it with the provided parameters.

        :param security: The security details required for authentication
        :param tenant_domain: Allows setting the tenantDomain variable for url substitution
        :param server_idx: The index of the server to use for all methods
        :param server_url: The server URL to use for all methods
        :param url_params: Parameters to optionally template the server URL with
        :param client: The HTTP client to use for all synchronous methods
        :param async_client: The Async HTTP client to use for all asynchronous methods
        :param retry_config: The retry configuration to use for all supported methods
        :param timeout_ms: Optional request timeout applied to each operation in milliseconds
        """
        client_supplied = True
        if client is None:
            client = httpx.Client(follow_redirects=True)
            client_supplied = False

        assert issubclass(
            type(client), HttpClient
        ), "The provided client must implement the HttpClient protocol."

        async_client_supplied = True
        if async_client is None:
            async_client = httpx.AsyncClient(follow_redirects=True)
            async_client_supplied = False

        if debug_logger is None:
            debug_logger = get_default_logger()

        assert issubclass(
            type(async_client), AsyncHttpClient
        ), "The provided async_client must implement the AsyncHttpClient protocol."

        if server_url is not None:
            if url_params is not None:
                server_url = utils.template_url(server_url, url_params)
        server_defaults: List[Dict[str, str]] = [
            {
                "tenantDomain": tenant_domain or "example",
            },
        ]

        BaseSDK.__init__(
            self,
            SDKConfiguration(
                client=client,
                client_supplied=client_supplied,
                async_client=async_client,
                async_client_supplied=async_client_supplied,
                security=security,
                server_url=server_url,
                server_idx=server_idx,
                server_defaults=server_defaults,
                retry_config=retry_config,
                timeout_ms=timeout_ms,
                debug_logger=debug_logger,
            ),
            parent_ref=self,
        )

        hooks = SDKHooks()

        # pylint: disable=protected-access
        self.sdk_configuration.__dict__["_hooks"] = hooks

        current_server_url, *_ = self.sdk_configuration.get_server_details()
        server_url, self.sdk_configuration.client = hooks.sdk_init(
            current_server_url, client
        )
        if current_server_url != server_url:
            self.sdk_configuration.server_url = server_url

        weakref.finalize(
            self,
            close_clients,
            cast(ClientOwner, self.sdk_configuration),
            self.sdk_configuration.client,
            self.sdk_configuration.client_supplied,
            self.sdk_configuration.async_client,
            self.sdk_configuration.async_client_supplied,
        )

    def dynamic_import(self, modname, retries=3):
        for attempt in range(retries):
            try:
                return importlib.import_module(modname)
            except KeyError:
                # Clear any half-initialized module and retry
                sys.modules.pop(modname, None)
                if attempt == retries - 1:
                    break
        raise KeyError(f"Failed to import module '{modname}' after {retries} attempts")

    def __getattr__(self, name: str):
        if name in self._sub_sdk_map:
            module_path, class_name = self._sub_sdk_map[name]
            try:
                module = self.dynamic_import(module_path)
                klass = getattr(module, class_name)
                instance = klass(self.sdk_configuration, parent_ref=self)
                setattr(self, name, instance)
                return instance
            except ImportError as e:
                raise AttributeError(
                    f"Failed to import module {module_path} for attribute {name}: {e}"
                ) from e
            except AttributeError as e:
                raise AttributeError(
                    f"Failed to find class {class_name} in module {module_path} for attribute {name}: {e}"
                ) from e

        raise AttributeError(
            f"'{type(self).__name__}' object has no attribute '{name}'"
        )

    def __dir__(self):
        default_attrs = list(super().__dir__())
        lazy_attrs = list(self._sub_sdk_map.keys())
        return sorted(list(set(default_attrs + lazy_attrs)))

    def __enter__(self):
        return self

    async def __aenter__(self):
        return self

    def __exit__(self, exc_type, exc_val, exc_tb):
        if (
            self.sdk_configuration.client is not None
            and not self.sdk_configuration.client_supplied
        ):
            self.sdk_configuration.client.close()
        self.sdk_configuration.client = None

    async def __aexit__(self, exc_type, exc_val, exc_tb):
        if (
            self.sdk_configuration.async_client is not None
            and not self.sdk_configuration.async_client_supplied
        ):
            await self.sdk_configuration.async_client.aclose()
        self.sdk_configuration.async_client = None
