"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
import httpx
from openapi.models.shared import searchpastgrantsresponse as shared_searchpastgrantsresponse
from openapi.types import BaseModel
from typing import Optional, TypedDict
from typing_extensions import NotRequired


class C1APIAppV1AppEntitlementUserBindingServiceSearchPastGrantsResponseTypedDict(TypedDict):
    content_type: str
    r"""HTTP response content type for this operation"""
    status_code: int
    r"""HTTP response status code for this operation"""
    raw_response: httpx.Response
    r"""Raw HTTP response; suitable for custom response parsing"""
    search_past_grants_response: NotRequired[shared_searchpastgrantsresponse.SearchPastGrantsResponseTypedDict]
    r"""The SearchPastGrantsRequest message contains a list of results and a nextPageToken if applicable."""
    

class C1APIAppV1AppEntitlementUserBindingServiceSearchPastGrantsResponse(BaseModel):
    content_type: str
    r"""HTTP response content type for this operation"""
    status_code: int
    r"""HTTP response status code for this operation"""
    raw_response: httpx.Response
    r"""Raw HTTP response; suitable for custom response parsing"""
    search_past_grants_response: Optional[shared_searchpastgrantsresponse.SearchPastGrantsResponse] = None
    r"""The SearchPastGrantsRequest message contains a list of results and a nextPageToken if applicable."""
    
