workflowVersion: 1.0.0
sources:
    my-source:
        inputs:
            - location: https://insulator.conductor.one/api/v1/openapi.yaml
targets:
    conductorone-python:
        target: python
        source: my-source
