name: Generate
permissions:
  checks: write
  contents: write
  pull-requests: write
  statuses: write
on:
  workflow_dispatch:
    inputs:
      force:
        description: "Force the generation of the SDKs"
        type: boolean
        default: false
  schedule:
    - cron: 0 0 * * *

jobs:
  generate:
    uses: speakeasy-api/sdk-generation-action/.github/workflows/sdk-generation.yaml@v14
    with:
      speakeasy_version: latest
      openapi_docs: |
        - https://insulator.conductor.one/api/v1/openapi.yaml
      languages: |-
        - python
      mode: pr
      publish_python: false
      force: ${{ github.event.inputs.force }}
    secrets:
      github_access_token: ${{ secrets.GITHUB_TOKEN }}
      speakeasy_api_key: ${{ secrets.SPEAKEASY_API_KEY }}
      slack_webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}
  
