"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from conductorone_sdk.models.shared import (
    functionsservicelisttagsresponse as shared_functionsservicelisttagsresponse,
)
from conductorone_sdk.types import BaseModel
from conductorone_sdk.utils import FieldMetadata, PathParamMetadata
import httpx
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class C1APIFunctionsV1FunctionsServiceListTagsRequestTypedDict(TypedDict):
    function_id: str


class C1APIFunctionsV1FunctionsServiceListTagsRequest(BaseModel):
    function_id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]


class C1APIFunctionsV1FunctionsServiceListTagsResponseTypedDict(TypedDict):
    content_type: str
    r"""HTTP response content type for this operation"""
    status_code: int
    r"""HTTP response status code for this operation"""
    raw_response: httpx.Response
    r"""Raw HTTP response; suitable for custom response parsing"""
    functions_service_list_tags_response: NotRequired[
        shared_functionsservicelisttagsresponse.FunctionsServiceListTagsResponseTypedDict
    ]
    r"""Successful response"""


class C1APIFunctionsV1FunctionsServiceListTagsResponse(BaseModel):
    content_type: str
    r"""HTTP response content type for this operation"""

    status_code: int
    r"""HTTP response status code for this operation"""

    raw_response: httpx.Response
    r"""Raw HTTP response; suitable for custom response parsing"""

    functions_service_list_tags_response: Optional[
        shared_functionsservicelisttagsresponse.FunctionsServiceListTagsResponse
    ] = None
    r"""Successful response"""
