"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from conductorone_sdk.models.shared import (
    vaultserviceupdaterequest as shared_vaultserviceupdaterequest,
    vaultserviceupdateresponse as shared_vaultserviceupdateresponse,
)
from conductorone_sdk.types import BaseModel
from conductorone_sdk.utils import FieldMetadata, PathParamMetadata, RequestMetadata
import httpx
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class C1APIVaultV1VaultServiceUpdateRequestTypedDict(TypedDict):
    id: str
    vault_service_update_request: NotRequired[
        shared_vaultserviceupdaterequest.VaultServiceUpdateRequestTypedDict
    ]


class C1APIVaultV1VaultServiceUpdateRequest(BaseModel):
    id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]

    vault_service_update_request: Annotated[
        Optional[shared_vaultserviceupdaterequest.VaultServiceUpdateRequest],
        FieldMetadata(request=RequestMetadata(media_type="application/json")),
    ] = None


class C1APIVaultV1VaultServiceUpdateResponseTypedDict(TypedDict):
    content_type: str
    r"""HTTP response content type for this operation"""
    status_code: int
    r"""HTTP response status code for this operation"""
    raw_response: httpx.Response
    r"""Raw HTTP response; suitable for custom response parsing"""
    vault_service_update_response: NotRequired[
        shared_vaultserviceupdateresponse.VaultServiceUpdateResponseTypedDict
    ]
    r"""Successful response"""


class C1APIVaultV1VaultServiceUpdateResponse(BaseModel):
    content_type: str
    r"""HTTP response content type for this operation"""

    status_code: int
    r"""HTTP response status code for this operation"""

    raw_response: httpx.Response
    r"""Raw HTTP response; suitable for custom response parsing"""

    vault_service_update_response: Optional[
        shared_vaultserviceupdateresponse.VaultServiceUpdateResponse
    ] = None
    r"""Successful response"""
