"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from conductorone_sdk.models.shared import (
    webhookssearchresponse as shared_webhookssearchresponse,
)
from conductorone_sdk.types import BaseModel
import httpx
from typing import Callable, Optional
from typing_extensions import NotRequired, TypedDict


class C1APIWebhooksV1WebhooksSearchSearchResponseTypedDict(TypedDict):
    content_type: str
    r"""HTTP response content type for this operation"""
    status_code: int
    r"""HTTP response status code for this operation"""
    raw_response: httpx.Response
    r"""Raw HTTP response; suitable for custom response parsing"""
    webhooks_search_response: NotRequired[
        shared_webhookssearchresponse.WebhooksSearchResponseTypedDict
    ]
    r"""Successful response"""


class C1APIWebhooksV1WebhooksSearchSearchResponse(BaseModel):
    next: Callable[[], Optional[C1APIWebhooksV1WebhooksSearchSearchResponse]]

    content_type: str
    r"""HTTP response content type for this operation"""

    status_code: int
    r"""HTTP response status code for this operation"""

    raw_response: httpx.Response
    r"""Raw HTTP response; suitable for custom response parsing"""

    webhooks_search_response: Optional[
        shared_webhookssearchresponse.WebhooksSearchResponse
    ] = None
    r"""Successful response"""
