"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from conductorone_sdk.models.shared import (
    listappowneridsresponse as shared_listappowneridsresponse,
)
from conductorone_sdk.types import BaseModel
from conductorone_sdk.utils import FieldMetadata, PathParamMetadata
import httpx
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class C1APIAppV1AppOwnersListOwnerIDsRequestTypedDict(TypedDict):
    app_id: str


class C1APIAppV1AppOwnersListOwnerIDsRequest(BaseModel):
    app_id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]


class C1APIAppV1AppOwnersListOwnerIDsResponseTypedDict(TypedDict):
    content_type: str
    r"""HTTP response content type for this operation"""
    status_code: int
    r"""HTTP response status code for this operation"""
    raw_response: httpx.Response
    r"""Raw HTTP response; suitable for custom response parsing"""
    list_app_owner_i_ds_response: NotRequired[
        shared_listappowneridsresponse.ListAppOwnerIDsResponseTypedDict
    ]
    r"""The response message for listing app owners IDs."""


class C1APIAppV1AppOwnersListOwnerIDsResponse(BaseModel):
    content_type: str
    r"""HTTP response content type for this operation"""

    status_code: int
    r"""HTTP response status code for this operation"""

    raw_response: httpx.Response
    r"""Raw HTTP response; suitable for custom response parsing"""

    list_app_owner_i_ds_response: Optional[
        shared_listappowneridsresponse.ListAppOwnerIDsResponse
    ] = None
    r"""The response message for listing app owners IDs."""
