"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from conductorone_sdk.models.shared import (
    updatestepupproviderrequest as shared_updatestepupproviderrequest,
    updatestepupproviderresponse as shared_updatestepupproviderresponse,
)
from conductorone_sdk.types import BaseModel
from conductorone_sdk.utils import FieldMetadata, PathParamMetadata, RequestMetadata
import httpx
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class C1APIStepupV1StepUpProviderServiceUpdateRequestTypedDict(TypedDict):
    id: str
    update_step_up_provider_request: NotRequired[
        shared_updatestepupproviderrequest.UpdateStepUpProviderRequestTypedDict
    ]


class C1APIStepupV1StepUpProviderServiceUpdateRequest(BaseModel):
    id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]

    update_step_up_provider_request: Annotated[
        Optional[shared_updatestepupproviderrequest.UpdateStepUpProviderRequest],
        FieldMetadata(request=RequestMetadata(media_type="application/json")),
    ] = None


class C1APIStepupV1StepUpProviderServiceUpdateResponseTypedDict(TypedDict):
    content_type: str
    r"""HTTP response content type for this operation"""
    status_code: int
    r"""HTTP response status code for this operation"""
    raw_response: httpx.Response
    r"""Raw HTTP response; suitable for custom response parsing"""
    update_step_up_provider_response: NotRequired[
        shared_updatestepupproviderresponse.UpdateStepUpProviderResponseTypedDict
    ]
    r"""Successful response"""


class C1APIStepupV1StepUpProviderServiceUpdateResponse(BaseModel):
    content_type: str
    r"""HTTP response content type for this operation"""

    status_code: int
    r"""HTTP response status code for this operation"""

    raw_response: httpx.Response
    r"""Raw HTTP response; suitable for custom response parsing"""

    update_step_up_provider_response: Optional[
        shared_updatestepupproviderresponse.UpdateStepUpProviderResponse
    ] = None
    r"""Successful response"""
