"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from conductorone_sdk.models.shared import (
    getuserprofiletypesresponse as shared_getuserprofiletypesresponse,
)
from conductorone_sdk.types import BaseModel
from conductorone_sdk.utils import FieldMetadata, PathParamMetadata
import httpx
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class C1APIUserV1UserServiceGetUserProfileTypesRequestTypedDict(TypedDict):
    user_id: str


class C1APIUserV1UserServiceGetUserProfileTypesRequest(BaseModel):
    user_id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]


class C1APIUserV1UserServiceGetUserProfileTypesResponseTypedDict(TypedDict):
    content_type: str
    r"""HTTP response content type for this operation"""
    status_code: int
    r"""HTTP response status code for this operation"""
    raw_response: httpx.Response
    r"""Raw HTTP response; suitable for custom response parsing"""
    get_user_profile_types_response: NotRequired[
        shared_getuserprofiletypesresponse.GetUserProfileTypesResponseTypedDict
    ]
    r"""Successful response"""


class C1APIUserV1UserServiceGetUserProfileTypesResponse(BaseModel):
    content_type: str
    r"""HTTP response content type for this operation"""

    status_code: int
    r"""HTTP response status code for this operation"""

    raw_response: httpx.Response
    r"""Raw HTTP response; suitable for custom response parsing"""

    get_user_profile_types_response: Optional[
        shared_getuserprofiletypesresponse.GetUserProfileTypesResponse
    ] = None
    r"""Successful response"""
