"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from conductorone_sdk.models.shared import (
    createcomplianceframeworkattributevalueresponse as shared_createcomplianceframeworkattributevalueresponse,
)
from conductorone_sdk.types import BaseModel
import httpx
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class C1APIAttributeV1AttributesCreateComplianceFrameworkAttributeValueResponseTypedDict(
    TypedDict
):
    content_type: str
    r"""HTTP response content type for this operation"""
    status_code: int
    r"""HTTP response status code for this operation"""
    raw_response: httpx.Response
    r"""Raw HTTP response; suitable for custom response parsing"""
    create_compliance_framework_attribute_value_response: NotRequired[
        shared_createcomplianceframeworkattributevalueresponse.CreateComplianceFrameworkAttributeValueResponseTypedDict
    ]
    r"""Successful response"""


class C1APIAttributeV1AttributesCreateComplianceFrameworkAttributeValueResponse(
    BaseModel
):
    content_type: str
    r"""HTTP response content type for this operation"""

    status_code: int
    r"""HTTP response status code for this operation"""

    raw_response: httpx.Response
    r"""Raw HTTP response; suitable for custom response parsing"""

    create_compliance_framework_attribute_value_response: Optional[
        shared_createcomplianceframeworkattributevalueresponse.CreateComplianceFrameworkAttributeValueResponse
    ] = None
    r"""Successful response"""
