"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from conductorone_sdk.models.shared import (
    conflictmonitordeleterequest as shared_conflictmonitordeleterequest,
    conflictmonitordeleteresponse as shared_conflictmonitordeleteresponse,
)
from conductorone_sdk.types import BaseModel
from conductorone_sdk.utils import FieldMetadata, PathParamMetadata, RequestMetadata
import httpx
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class C1APIAccessconflictV1AccessConflictServiceDeleteMonitorRequestTypedDict(
    TypedDict
):
    id: str
    conflict_monitor_delete_request: NotRequired[
        shared_conflictmonitordeleterequest.ConflictMonitorDeleteRequestTypedDict
    ]


class C1APIAccessconflictV1AccessConflictServiceDeleteMonitorRequest(BaseModel):
    id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]

    conflict_monitor_delete_request: Annotated[
        Optional[shared_conflictmonitordeleterequest.ConflictMonitorDeleteRequest],
        FieldMetadata(request=RequestMetadata(media_type="application/json")),
    ] = None


class C1APIAccessconflictV1AccessConflictServiceDeleteMonitorResponseTypedDict(
    TypedDict
):
    content_type: str
    r"""HTTP response content type for this operation"""
    status_code: int
    r"""HTTP response status code for this operation"""
    raw_response: httpx.Response
    r"""Raw HTTP response; suitable for custom response parsing"""
    conflict_monitor_delete_response: NotRequired[
        shared_conflictmonitordeleteresponse.ConflictMonitorDeleteResponseTypedDict
    ]
    r"""Successful response"""


class C1APIAccessconflictV1AccessConflictServiceDeleteMonitorResponse(BaseModel):
    content_type: str
    r"""HTTP response content type for this operation"""

    status_code: int
    r"""HTTP response status code for this operation"""

    raw_response: httpx.Response
    r"""Raw HTTP response; suitable for custom response parsing"""

    conflict_monitor_delete_response: Optional[
        shared_conflictmonitordeleteresponse.ConflictMonitorDeleteResponse
    ] = None
    r"""Successful response"""
