"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from conductorone_sdk.models.shared import (
    connectorservicerotatecredentialresponse as shared_connectorservicerotatecredentialresponse,
)
from conductorone_sdk.types import BaseModel
import httpx
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class C1APIAppV1ConnectorServiceRotateCredentialResponseTypedDict(TypedDict):
    content_type: str
    r"""HTTP response content type for this operation"""
    status_code: int
    r"""HTTP response status code for this operation"""
    raw_response: httpx.Response
    r"""Raw HTTP response; suitable for custom response parsing"""
    connector_service_rotate_credential_response: NotRequired[
        shared_connectorservicerotatecredentialresponse.ConnectorServiceRotateCredentialResponseTypedDict
    ]
    r"""ConnectorServiceRotateCredentialResponse is the response returned by the rotate method."""


class C1APIAppV1ConnectorServiceRotateCredentialResponse(BaseModel):
    content_type: str
    r"""HTTP response content type for this operation"""

    status_code: int
    r"""HTTP response status code for this operation"""

    raw_response: httpx.Response
    r"""Raw HTTP response; suitable for custom response parsing"""

    connector_service_rotate_credential_response: Optional[
        shared_connectorservicerotatecredentialresponse.ConnectorServiceRotateCredentialResponse
    ] = None
    r"""ConnectorServiceRotateCredentialResponse is the response returned by the rotate method."""
