"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from conductorone_sdk.models.shared import (
    requestcatalogmanagementserviceaddaccessentitlementsrequest as shared_requestcatalogmanagementserviceaddaccessentitlementsrequest,
    requestcatalogmanagementserviceaddaccessentitlementsresponse as shared_requestcatalogmanagementserviceaddaccessentitlementsresponse,
)
from conductorone_sdk.types import BaseModel
from conductorone_sdk.utils import FieldMetadata, PathParamMetadata, RequestMetadata
import httpx
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class C1APIRequestcatalogV1RequestCatalogManagementServiceAddAccessEntitlementsRequestTypedDict(
    TypedDict
):
    catalog_id: str
    request_catalog_management_service_add_access_entitlements_request: NotRequired[
        shared_requestcatalogmanagementserviceaddaccessentitlementsrequest.RequestCatalogManagementServiceAddAccessEntitlementsRequestTypedDict
    ]


class C1APIRequestcatalogV1RequestCatalogManagementServiceAddAccessEntitlementsRequest(
    BaseModel
):
    catalog_id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]

    request_catalog_management_service_add_access_entitlements_request: Annotated[
        Optional[
            shared_requestcatalogmanagementserviceaddaccessentitlementsrequest.RequestCatalogManagementServiceAddAccessEntitlementsRequest
        ],
        FieldMetadata(request=RequestMetadata(media_type="application/json")),
    ] = None


class C1APIRequestcatalogV1RequestCatalogManagementServiceAddAccessEntitlementsResponseTypedDict(
    TypedDict
):
    content_type: str
    r"""HTTP response content type for this operation"""
    status_code: int
    r"""HTTP response status code for this operation"""
    raw_response: httpx.Response
    r"""Raw HTTP response; suitable for custom response parsing"""
    request_catalog_management_service_add_access_entitlements_response: NotRequired[
        shared_requestcatalogmanagementserviceaddaccessentitlementsresponse.RequestCatalogManagementServiceAddAccessEntitlementsResponseTypedDict
    ]
    r"""Empty response with a status code indicating success."""


class C1APIRequestcatalogV1RequestCatalogManagementServiceAddAccessEntitlementsResponse(
    BaseModel
):
    content_type: str
    r"""HTTP response content type for this operation"""

    status_code: int
    r"""HTTP response status code for this operation"""

    raw_response: httpx.Response
    r"""Raw HTTP response; suitable for custom response parsing"""

    request_catalog_management_service_add_access_entitlements_response: Optional[
        shared_requestcatalogmanagementserviceaddaccessentitlementsresponse.RequestCatalogManagementServiceAddAccessEntitlementsResponse
    ] = None
    r"""Empty response with a status code indicating success."""
